### ISSUE TITLE
[Frontend] Publisher Admin Panel

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#1019]

**Comment by mxosman** [comment]
MVP completed. Reference issues: #1104, #1075, #1058, #1069, #1051, #1052, #1090, #1050, #1053, #1054, #1049, #1048, #1039

**Comment by lilidworkin** [comment]
<img src="https://media3.giphy.com/media/1q9addeaZMx020Gv8u/giphy.gif"/>

**Comment by mxosman** [comment]
<img src="https://media2.giphy.com/media/zD2SpVI4vBLeo/giphy.gif"/>
