### ISSUE TITLE
[Publisher] Admin Panel: Create New User/Agency from both Provisioning Flows

### ISSUE THREAD

**Issue by mxosman** [Recidiviz/justice-counts#1058]

**Comment by morden35** [comment]
@mxosman could this be moved to in-progress?

**Comment by mxosman** [comment]
Hi Michelle! I'm not there yet, but will move it over as soon as I start work on it - it's fleshing out the flow where you can quickly create a new agency while creating a user - vice versa - quickly create a user while creating an agency. This might end up being a P2 because it's a bit more involved and I'm still debating whether or not it's really necessary.
