### ISSUE TITLE
[Security] `npm` vulnerabilities October 21, 2022

### ISSUE THREAD

**Issue by phenggeler** [Recidiviz/justice-counts#106]
**What needs to be done? Why does it need to be done?**
Please review the following CVEs and determine whether we should fix the issue or dismiss the alert. If we decide to dismiss the alert, please document why we did so and dismiss the Dependabot alert.

- https://github.com/Recidiviz/justice-counts/security/dependabot/7
- https://github.com/Recidiviz/justice-counts/security/dependabot/6
- https://github.com/Recidiviz/justice-counts/security/dependabot/5

**Additional context**
Add any other context about the task here.

**Comment by lilidworkin** [comment]
@terryttsai could you take a look at this? It looks like we have minimatch=3.0.4, is it possible to upgrade to 3.0.5? Not sure why dependabot is saying that "No security update is needed as minimatch is no longer vulnerable".

**Comment by phenggeler** [comment]
@lilidworkin and @terryttsai - Dependabot does that from time-to-time. It is fair to dismiss these alerts since they are no longer vulnerable, or you can go ahead and upgrade the package. I will leave it up to you! 

If you do dismiss the alert, could you please just add a comment like `According to Github, Dependabot hasn't attempted to update minimatch as it's no longer vulnerable. Dismissing this since the package is no longer vulnerable.`

**Comment by lilidworkin** [comment]
Thanks @phenggeler ! Dismissed all alerts with that comment.

Closing this task since all alerts have been closed.
