### ISSUE TITLE
[Justice Counts] Add 'Define Metrics' arrow for metrics without breakdowns

### ISSUE THREAD

**Issue by morden35** [Recidiviz/justice-counts#1093]
On 12/08/23, Laura from CSG was doing metric configuration for a Supervision agency and noticed that the Reconvictions metric did not have the "Define Metrics -->" button on the "Set metric availability" page that other metrics have (slack thread [here](https://recidiviz.slack.com/archives/C04JL8A2ADB/p1702052202185199)). This is not a bug per se, but caused some confusion during the configuration process. The reason this metric was missing the "Define Metrics -->" button is because the Reconvictions metric does not have breakdowns. Currently, the "Define Metrics -->" button only appears for metrics that have breakdowns.
<img width="296" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1ZGQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e24564d7b504fc6ae57e4ab8697337c4ecf2fa4a/Screenshot%202023-12-08%20at%2012.04.55%E2%80%AFPM.png" alt="Screenshot 2023-12-08 at 12.04.55 PM.png" />

Metric that has breakdowns
<img width="1083" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1JGQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--11b4dc04f0d30dfbf3c9cb99d85fed3d9a947d7a/Screenshot%202023-12-08%20at%2012.04.50%E2%80%AFPM.png" alt="Screenshot 2023-12-08 at 12.04.50 PM.png" />

Metric that does not have breakdowns
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTlGQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe308543d749b1de9e2451d4b9bf0172753451dd/image.png" alt="image.png" />

Per request, please include the "Define Metrics -->" button for all metrics (regardless of whether or not they have breakdowns)!

**Comment by mxosman** [comment]
Thank you, Michelle!!
