### ISSUE TITLE
[Publisher] When you click into a Record, the Agency Name in the top bar goes away

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#1138]
I noticed this during playtesting and it bugged me a little! If it's an easy fix we can just knock it out, else feel free to ignore :)

<img width="232" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVRCQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--776b75446f9c271303c7bcca4ddd61c9fbd15286/Screenshot%202024-01-12%20at%209.25.00%E2%80%AFAM.png" alt="Screenshot 2024-01-12 at 9.25.00 AM.png" />

**Comment by mxosman** [comment]
Haha - sounds great, Lili! Will do! I'll have to check the behavior of switching agencies while having a record open to see if redirects - I don't think it does, but we don't necessarily need the dropdown. At the very least, we can put the agency name in the same style (like we do now for single agency users).
