### ISSUE TITLE
[Publisher] Offset picker for email notifications

### ISSUE THREAD

**Issue by jwhrec** [Recidiviz/justice-counts#1207]
As requested by CSG, we are adding a feature to allow users to decide when to receive emails reminding them to upload metrics. The user can input a number n from 1-1000. They would receive an email n days after the 1st day of the following reporting period. 

See [figma here.](**url**) 

The FE will use the same API endpoint that is currently used for `AgencyStore.updateIsUserSubscribedToEmails` (`/api/agency/<agency_id>/subscription/<user_id>`) to update the offset. Now this endpoint will receive an argument called `days_after_time_period_to_send_email`. The BE expects this argument to be a positive integer. The BE will send a 200 OK response if we can successfully update the user's specified offset. **The BE expects both `is_subscribed` and `days_after_time_period_to_send_email` to be in the API request.** 

The BE will also now send `days_after_time_period_to_send_email` when the FE fetches the agency setting's for a user with` AgencyStore.getAgencySettings`.  The response will now look like this: 

```
 {
                    "settings": []AgencySettings,
                    "jurisdictions":[]Jurisdictions,
                    "is_subscribed_to_emails":bool,
                    "days_after_time_period_to_send_email": int

  }
```
You can use the `days_after_time_period_to_send_email` to populate the offset picker when the user loads the page. If `days_after_time_period_to_send_email` is null, **the FE should default the option to 15.**

**Comment by mxosman** [comment]
Hi @jwhrec! I think the Figma link is broken in the description. Is this the right Figma node for this feature - https://www.figma.com/file/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?type=design&node-id=10571%3A13082&mode=design&t=AmbobtUdVoXs897I-1?

**Comment by jwhrec** [comment]
so sorry I missed this - but you were correct, glad you got unblocked quickly. Sorry for any confusion I caused!

**Comment by mxosman** [comment]
> so sorry I missed this - but you were correct, glad you got unblocked quickly. Sorry for any confusion I caused!

Hi @jwhrec! Omg - please don't apologize one bit! I totally answered my own question and completely forgot I asked it until I just read this. 😄
