### ISSUE TITLE
[Publisher] [Admin Panel] Don't allow user's to be added to an agency without a role

### ISSUE THREAD

**Issue by nichelle-hall** [Recidiviz/justice-counts#1233]
[This]([Justice Counts] [Admin Panel] Don't allow user's to be added to an agency without a role) sentry error was surfaced because a user with no role tried to create a report. Users should not be able to be added to an agency without a role.

**Comment by lilidworkin** [comment]
Closing in favor of https://app.zenhub.com/workspaces/justice-counts--622109ea3bb6e0001d2d06ad/issues/gh/recidiviz/recidiviz-data/28218
