### ISSUE TITLE
Get set up for development on Justice Counts Publisher

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#1234]
Steps to get setup for development on the Justice Counts Publisher application:

1) Clone [this repo](https://github.com/Recidiviz/justice-counts)
2) `cd` into the `publisher` subdirectory (this is where you will be doing most of your development, though there are some components in the `common` subdirectory that you'll be using)
3) Make a copy of `.env.example` and rename it to `.env`
4) In `.env`, replace `http://localhost:5001` with `https://publisher-staging.justice-counts.org/`. This means that when you run the application locally, it will use our staging backend API.
5) Run `yarn install`
6) Run `yarn run dev`
7) You should see a dialog prompting you to login. An account has been created for you already! Check your email for instructions to set your password.
8) Feel free to explore the app. You can make any changes you want -- it will only affect our staging database.

If you have any trouble, leave a comment on this task and tag @mxosman and @lilidworkin !

For any PRs you put up, please add @mxosman and @lilidworkin as reviewers. Thank you!

**Comment by nasaownsky** [comment]
Everything works like a charm, thank you @lilidworkin!
