### ISSUE TITLE
[Publisher][Admin Panel][1/n] Agency Provisioning: Make it possible to choose metrics/child agencies during metric copy

### ISSUE THREAD

**Issue by mxosman** [Recidiviz/justice-counts#1248]
### Overview

We have a notion of a “Superagency”, which is an agency that “controls” other agencies. For example, “NM Legislative Finance Committee” is a superagency with 5 child agencies (you should have access to all of these agencies in Publisher, and be able to switch between them via the dropdown in the top left).

When you open a superagency in the Admin Panel, you will see an option to “copy all metric settings to child agencies across all sectors”:

<img width="323" alt="Screenshot 2024-03-19 at 10 28 53 AM" src="https://github.com/Recidiviz/justice-counts/assets/59492998/16cb3258-ba4d-48c8-a9a5-d77bdb902ca1">

We want to change this so the user has more control over what happens here. In particular, we want to let the user pick:

- Which metrics to copy
- Which child agencies to copy

The [backend API](https://github.com/Recidiviz/justice-counts/blob/adffdf3be7e58da3c2c5fee01b821b02eadbfa95/publisher/src/stores/AdminPanelStore.ts#L222) currently supports both options via the following parameters:

- `metric_definition_key_subset`: list of strings of metric keys
- `child_agency_id_subset`: list of ints of child agency IDs (not yet merged, will be soon)

Currently, we are not yet passing in a value for `child_agency_id_subset`, and [we are passing in “ALL”](https://github.com/Recidiviz/justice-counts/blob/adffdf3be7e58da3c2c5fee01b821b02eadbfa95/publisher/src/components/AdminPanel/AgencyProvisioning.tsx#L278) for `metric_definition_key_subset` (which results in all metrics being copied over). After this task, we should be passing in lists for both parameters.

---
### Task 

Here are the changes we want to make:

Change the text that says “Copy all metric settings to child agencies across all sectors” to say “Copy metric settings to child agencies”.

If the user checks that box, we should do two things:
- Make a call to a new BE endpoint called /admin/agency/<agency_id> [GET]. 
  - Pass in the ID of the agency that is currently open. 
  - This endpoint will return a JSON blob with the key “metrics”. The value of that key is a list of dictionaries one for each metric that the user could choose to copy over. The dictionary will contain both the metric’s display name (what we should show in the UI), the metric’s key (what we should pass to the backend if the user selects this metric), and the metric’s sector (will be relevant in the second task).
- After the endpoint returns, we should show the user two more boxes:
  - One box where they can see all their child agencies and select a subset (we should already have access to information about all of this agency’s child agencies)
  -  One box where they can see all their metrics and select a subset (this box will be populated based on what the endpoint returns)

For both boxes, we should use the existing searchable box component (`<InteractiveSearchList ... />`) that lets the user click in and then select, deselect, and search from a list of options. 

The WARNING! box should still appear at the bottom of the modal, but the second sentence should now say “This will OVERWRITE metric settings in child agencies.” (basically take out the word “all” because it’s no longer true).

**Comment by morden35** [comment]
@mxosman can I move this to In Progress?

**Comment by mxosman** [comment]
Absolutely! I just moved it now! Thank you for the heads up, @morden35 !

**Comment by morden35** [comment]
Thank you @mxosman!
