### ISSUE TITLE
[Publisher][Design Update] Agency Settings: Team Members Tab (5/5)

### ISSUE THREAD

**Issue by mxosman** [Recidiviz/justice-counts#1259]
Update the design of the Team Members component and modal. This is the last piece of the Agency Settings design update. The input and modal bases should hopefully be ready to reuse from the neighboring components in the Settings folder (or common repo).

Reference: [Figma Node 1](https://www.figma.com/design/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?node-id=9418-3369&t=2QdVRB4OiW6g8kCU-4), [Figma Node 2](https://www.figma.com/design/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?node-id=10172-3523&t=2QdVRB4OiW6g8kCU-4)

Relevant File: src/components/Settings/AgencySettingsTeamManagement.tsx

 LMK if you have any questions or if I can help ramp you up in any way!

**Comment by lilidworkin** [comment]
Hey @corypride (cc @mxosman ) -- we are going to deprioritize this task for now because we have higher priority stuff, so I'm going to go ahead and unassign you!

**Comment by lilidworkin** [comment]
@mxosman I _think_ you have an in-progress PR for this -- would it make sense to just hand it over to Ilya and have him take it over? No problem if you would rather wait and come back to it, just figured I'd check!

**Comment by mxosman** [comment]
Hi @lilidworkin -- yeah, I totally overestimated my bandwidth. I'll update the ticket and assign it to Ilya before EOD!

**Comment by lilidworkin** [comment]
Awesome @mxosman , no rush at all!
