### ISSUE TITLE
Persist current metric after switching to a different child agency via the dropdown

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#1332]
With the new drop down for superagencies in Explore Data, would it be possible for the metric that is currently viewed to be the same metric viewed when you switch between child agencies?

**Comment by nichelle-hall** [comment]
@mxosman to you for now!

**Comment by nasaownsky** [comment]
Hi @lilidworkin! So I've looked through current functionality and codebase, and my question is: could you please be more specific with this task? I'm a little bit rusty with this project after switching to Insights and back again, and not exactly understand what's needed to be done here. Persist metric in what form? Like stay on the same page after switching? Or store previous metric somewhere? Thank you very much in advance!

**Comment by lilidworkin** [comment]
Of course, always please feel free to ask for more clarification @nasaownsky . I know it must be hard switching between these projects!

Actually now that I look into it, I'm not exactly sure what the idea was here :) Let me look into it and get back to you!

**Comment by lilidworkin** [comment]
@nasaownsky I _think_ the idea is this, but I'm going to confirm:

Say you are viewing a Superagency (like "Law Enforcement") and are on the Explore Page, and you are looking at the Expenses metric, like here: https://publisher-staging.justice-counts.org/agency/147/data?system=superagency&metric=superagency_expenses

Now, you use the dropdown that you previously implemented to switch to a child agency (like "AAB Delete", haha). After doing that, can we redirect to the same metric we were looking at previously, in this case Expenses? So the page that would load would be this one: https://publisher-staging.justice-counts.org/agency/371/data?system=law_enforcement&metric=law_enforcement_expenses

The problem is that the metric isn't _exactly_ the same -- one is superagency_expenses and the other one is law_enforcement_expenses -- so I'm not sure if this is technically tricky?

Also cc @mxosman for visibility

**Comment by lilidworkin** [comment]
Okay @nasaownsky actually ignore that comment -- it's simpler than that. The idea is if you are using the dropdown to _switch between child agencies in the same sector_, then we should stay on the same metric. So for example, if you are on Child Agency A, viewing the Arrests metric in the Law Enforcement sector, and you switch to Child Agency B, which also belongs to the Law Enforcement sector, then redirect to the page for the Law Enforcement Arrests metric for that agency.

For instance, if we are [here](https://publisher-staging.justice-counts.org/agency/371/data?system=law_enforcement&metric=law_enforcement_expenses&view=Count), on Child Agency AAB Delete, on Law Enforcement Expenses metric, and we use the dropdown to switch to AABB Delete, we should switch to the Law Enforcement Expenses page for that agency, i.e. [here](https://publisher-staging.justice-counts.org/agency/370/data?system=law_enforcement&metric=law_enforcement_expenses).

Let me and @mxosman know if that makes sense!

**Comment by mxosman** [comment]
Hi all! Thank you for the quick follow up, Lili! Hope you're taking it easy on yourself with the switching back and forth, @nasaownsky! I'm happy to help clarify further and help you ramp back up in any way I can!
