### ISSUE TITLE
[Frontend][Publisher][Redesign] Implement redesigned Data page

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#135]
**Designs**: https://www.figma.com/file/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?node-id=5470%3A15684

We have redesigned the page that you see when you click the "Data" tab in the top navigation bar. The main changes are as follows:

* The **left navigation** is redesigned.
          - Rather than the "boxes" you see now, it should just be a list of metric names. When active, the name should be underlined in blue.
          - @hobuobi: what is the hover state? And what should we do if the metric is disabled in settings?
* The chart and the dropdown controls above it are **unchanged**. (@hobuobi is this correct?)
* The **summary statistics** (i.e. Year-to-Year, Avg Value, Most Recent) have been moved. They are no longer underneath the dropdown controls, but rather off to the right of the metric name.
* Above the metric name, there are **two new links**: one which toggles a different, tabular view of the data (see the bullet below) and one which takes you to the corresponding Metric Configuration page in Settings.
* If you click the "Switch to Data Table" link, we now **render the data in tabular format**.   
         -  Ignore the "Publish All" button you see in the mocks for this page -- no need to build that yet.
         - For this page, you should be able to re-use some of the code / logic from [this similar existing page](https://www.figma.com/file/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?node-id=3952%3A10075) for Bulk Upload confirmation. To view this existing page, switch to a Law Enforcement agency, click "Upload Data" in the top right, and upload this file: [law_enforcement_success.xlsx](https://github.com/Recidiviz/justice-counts/files/9954211/law_enforcement_success.xlsx). You may see a page with some warnings -- ignore them and click Continue. Then you should see a confirmation page that displays the data in tabular format, very similar to how it should be displayed for this task.
         - @hobuobi: The table on the Bulk Upload confirmation page has borders between cells (see image below) -- is it okay to do the same for this table, or should we remove borders in both?
<img width="500" alt="Screen Shot 2022-11-07 at 12 56 22 PM" src="https://user-images.githubusercontent.com/99899591/200381183-d3d3b6e6-89b1-4333-9a1c-63f33be1e05b.png">

**Comment by hobuobi** [comment]
To answer the questions I'm tagged in above: 
- For the left hand menu: 
    - **Hover state** for the left-hand menu should be the same as the settings page for now, though I think we should think of something that is more noticeable (maybe make the unselected option lighter, or show an underline on hover? cc @agronomic). 
    - **Disabled metrics** should be omitted from this list (the disclaimer in the bottom-left corner clarifies that these are only the metrics that have been enabled in Metric Configuration). 
- **Controls** are unchanged from the previous version of this page (for now – I believe @agronomic is working on a new design for these and can update accordingly). 
- **Borders** on the table should be removed both here and on the Bulk Upload confirmation page.

**Comment by hobuobi** [comment]
One additional comment that just came to mind: 
The "Go to Metric Configuration" button should ideally take the user to the corresponding page in Settings – however, as far as I can tell, we don't use a different route for the different views on Settings (for example, when you're looking at Metric Configuration or a specific metric under Metric Configuration, the route is still "/settings"). Curious questions: 
1. Is it necessary to update that as part of this work
2. If not, do we want to do that anyway for legibility's sake
3. If we want to do it at all, should we create a separate ticket for it or not?

**Comment by ivan-kishko** [comment]
> One additional comment that just came to mind: The "Go to Metric Configuration" button should ideally take the user to the corresponding page in Settings – however, as far as I can tell, we don't use a different route for the different views on Settings (for example, when you're looking at Metric Configuration or a specific metric under Metric Configuration, the route is still "/settings"). Curious questions:
> 
> 1. Is it necessary to update that as part of this work
> 2. If not, do we want to do that anyway for legibility's sake
> 3. If we want to do it at all, should we create a separate ticket for it or not?

Hello @hobuobi. If I get this right, I can do so when you click "Go to metric configuration" app takes you to metric configuration menu item inside settings. I already did that in previous task so this should not be a problem.

**Comment by ivan-kishko** [comment]
Also @hobuobi can I ask about navigation bar. What is this - redesigned of the old one or this should appear when we are on data/upload page on top of default one? Anyway need some details what functionality this one should have.

**Comment by ivan-kishko** [comment]
One more thing. this agency "North Carolina Department of Public Safety (NCDPS)" has more than one system (I guess it is called system like in data entry). Old data page had functionality for this case implemented via tabs to switch between systems to look at corresponding system metrics. Can't see how new design is handling this.

**Comment by ivan-kishko** [comment]
@lilidworkin Hello Lili. About controls - I can see 3 dropdowns on new design whilst after checking all metrics of all agencies I saw only two - "Date Range" and "Disaggregation". What is "View" dropdown doing? Also I guess <code>Year-to-Year<code> on new design is <code>% Total Change</code> on old design (it is about summary statistics)?

**Comment by lilidworkin** [comment]
Hi @ivan-kishko ! Great questions as always!

1. Yes, that's right! I believe @mxosman made it possible to link directly to the Metric Configuration page in a recent PR. However, right now that always goes to the top-level Metric Configuration page that shows you a directory of all metrics. @ivan-kishko / @mxosman , how hard would it be to link directly to the configuration page for a _particular metric_?  If that's easy, maybe @ivan-kishko should make that change as well. Also with regards to your question @ivan-kishko about whether the text "metric configuration" in the bottom left should a link in blue color -- I think yes, it should be! Good catch.
2. @ivan-kishko are you asking about the *top* navigation bar? I think you can actually ignore those changes. Those shouldn't have made it into the Figma. The top navigation bar should stay the same.
3. @hobuobi is working on adding this to the new design! Great catch!
4. If you select a disaggregation, then a third dropdown ("View") appears! Video attached. For Year-to-Year --  yes you're right, I think that has been renamed to % Total Change (@hobuobi is that right? Is that mathematically correct?)
5. @hobuobi any thoughts on responsiveness?

**Comment by mxosman** [comment]
> Hi @ivan-kishko ! Great questions as always!
> 
> 1. Yes, that's right! I believe @mxosman made it possible to link directly to the Metric Configuration page in a recent PR. However, right now that always goes to the top-level Metric Configuration page that shows you a directory of all metrics. @ivan-kishko / @mxosman , how hard would it be to link directly to the configuration page for a _particular metric_?  If that's easy, maybe @ivan-kishko should make that change as well. Also with regards to your question @ivan-kishko about whether the text "metric configuration" in the bottom left should be a link in blue color -- I think yes, it should be! Good catch.

Hi Lili - that routing hasn't been fully implemented yet - I still have a branch pre-refactor exploring how difficult it will be. I wanted to wait to finish the refactor before proceeding any further on it because we'll need to store some query params and have the metric config components respond to those in order to get that direct link to the metric. 

It shouldn't be difficult to at the very least separate the settings into their own separate routes (most of that's pretty much done - just have to plug it in to the latest main and wire it up). That would at least get the first step of linking to this metric-config setting page directly with Metric Config highlighted in the menu. The next step after that would be to extend those routes to include query params like (activeMetricKey, activeSystemKey, etc.) and have the components do all their loading and initialization from the backend response, update the query params, and retrieve from the query params - which is a little trickier.

**Comment by lilidworkin** [comment]
@mxosman / @ivan-kishko , just to be clear, let's separate this discussion into two pieces:

1) Being able to link to a _particular page_ in Settings (e.g. Uploaded Files, Metric Configuration)
2) Being able to link to a _particular metric_ in Metric Configuration (e.g. Total Arrests)

It looks like @ivan-kishko did _some version_ of #1 -- there isn't a separate URL, but we can use Javascript to go straight to the page via `onClick={() => navigate("/settings", { state: navigateState })}`.

So my questions are:

A) Would it be possible to actually have different URLs for each page in Settings? That way, if you refresh the page, you stay where you are.
B) Would it be possible to have different URLs for each metric in Metric Configuration?

@ivan-kishko , what do you think?

**Comment by lilidworkin** [comment]
@mxosman to be clear I don't think you need to do any of this -- @ivan-kishko  can take it over!

**Comment by mxosman** [comment]
> Though @mxosman if you did do some work on 1) already, maybe you can put that up in a draft PR (no need to clean it up or rebase) that @ivan-kishko can reference and use for inspiration?

Absolutely! Here's a draft PR of how I was approaching it - feel free to use/come up with a better approach:
https://github.com/Recidiviz/justice-counts/pull/139

**Comment by mxosman** [comment]
> > Though @mxosman if you did do some work on 1) already, maybe you can put that up in a draft PR (no need to clean it up or rebase) that @ivan-kishko can reference and use for inspiration?
> 
> Absolutely! Here's a draft PR of how I was approaching it - feel free to use/come up with a better approach: #139 (I just rebased it - so it might be out of sync in a few components - but the naive routing implementation should be there)

**Comment by hobuobi** [comment]
Numbered responses correspond to @lilidworkin 's comments [above](https://github.com/Recidiviz/justice-counts/issues/135#issuecomment-1307598191): 

1. (Discussion ongoing in thread.) 
2. Yes, you can ignore those changes. Just updated the mocks to better reflect the current state of the application.  
3. Designed a solution for multiple systems that is now reflected in the designs (included below for reference). One thing that might not be obvious from the static designs is that only one section should be expanded at a time; for example, if you were to click on the "Parole" header in the mocks, that section would expand and the Prison section would collapse. Animation is not necessary right now unless you want to have fun with it ;) 
4. Yes, this should follow whatever the application is currently doing. I think we could still revise the math though. 
5. Created one view to show how the components should resize at half-width. No need to worry about anything smaller than this for now. 

![Screen (42)](https://user-images.githubusercontent.com/7134733/200687476-a51076d2-f24d-4731-ae65-fcff8a0fb0b4.png)
