### ISSUE TITLE
[Publisher] Group child agency dropdowns by sector

### ISSUE THREAD

**Issue by mxosman** [Recidiviz/justice-counts#1358]
Group the child agency dropdowns that appear for superagencies (in Set Up Metrics and Explore Data pages) by their unique sectors.

This is the last section of the original task in #1275:
>If the child agencies differ in the systems they belong to -- for instance if some of the child agencies belong to Law Enforcement and some to Courts -- we want to add sections to the dropdown and group the child agencies by which systems they belong to. They should be sorted alphabetically within each section. Reach out to @mxosman and @forrestkim00 when you get to this part for more clarity!

Reference: [Figma](https://www.figma.com/design/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?node-id=11652-6657&t=IBLfdBRyZcHOFDoG-4)
Relevant files: MetricsOverview.tsx, MetricsDataChart.tsx, ChildAgenciesDropdown.tsx

Quick notes: 
* if a child agency belongs to multiple sectors, it can appear multiple times under each sector heading it belongs to. For example, Child Agency A has both Defense and Jails, it will appear under Defense, and again under Jails.
* this may be obvious, but no need to show the sectors on the dropdown that have no child agencies belonging to them

**Comment by lilidworkin** [comment]
@mxosman did CSG ask for this? should we ask Forrest for designs and assign to Ilya?

**Comment by mxosman** [comment]
Hi @lilidworkin! This was just once piece of this task https://github.com/Recidiviz/justice-counts/issues/1275 that I decided to punt on (earlier comment: https://github.com/Recidiviz/justice-counts/pull/1295#issuecomment-2067347732 - I can't remember why... maybe it didn't feel high priority at the time/Ilya had already pivoted to another project?) and I've only now embarrassingly gotten around to making a task for it.

I think designs will definitely help and this can totally be assigned! Shall I make a request to Forrest?

**Comment by lilidworkin** [comment]
Yes that would be great, thanks!
