### ISSUE TITLE
[Publisher] Toggle between metric reporting frequencies in "Explore Data" tab

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#1368]
Agencies want to be able to view both CY and FY data on the same chart in the Explore Data page. Rather than allowing mixed frequency data to show on the same chart, we want to add some sort of toggle on the Explore Data page so that agencies can switch back and forth between CY, FY, and monthly charts.

[Implementation Notes from @mxosman]

Reference: [Figma Design](https://www.figma.com/design/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?node-id=11652-6610&t=IBLfdBRyZcHOFDoG-4)

* Quick note: all of the notes on both panels are relevant, but since Explore Data page is still in the old design, please reference the right panel for how it should look.
* Additional things included are:
    * updating the copy for one of the time period dropdown options ("All" to "All time")
    * updating the copy for text below the chart
    * removing the blue banner

Relevant files: [MetricsDataChart.tsx](https://github.com/Recidiviz/justice-counts/blob/main/publisher/src/components/DataViz/MetricsDataChart.tsx), [DatapointsStore.ts](https://github.com/Recidiviz/justice-counts/blob/main/publisher/src/stores/DatapointsStore.ts)

The dropdown will contain all of the unique frequencies extracted from all of the datapoints an agency produced.

Example: if an agency has recorded data for a monthly metric, calendar year metric (starting month in January), fiscal year metric (starting month in July), and an annual metric with a custom starting month (let's say March) -- the dropdown should include the following options: "Monthly", "Calendar Year", "Fiscal Year", "Annual: March".

Since we get a list of all datapoints, we can loop through them and group them in their respective unique frequency bucket and give users the option to filter the chart data by frequency.

Please connect with me (@mxosman) if you have any questions at all (or if I can help you ramp up)!

**Comment by mxosman** [comment]
Hi @nasaownsky - please always feel free to give me feedback on these tasks - whether they give you enough information, or not enough information, or if you think of any additional information I can include that would help make your life easier and reduce ramp up time as you switch contexts!

**Comment by nasaownsky** [comment]
Hi @mxosman! So I trying figure out this frequency breakdown. I see that datapoints have "frequency" parameter, that in some metrics has "ANNUAL" value, and in some "MONTHLY". Could you please explain how exactly this filtering should work  in conjunction with this parameter?

**Comment by nasaownsky** [comment]
So, does that mean that if the metric only has ANNUAL frequency datapoints they must be filtered only by annual options based on different starting months; and if it only has MONTHLY datapoints they must be only filtered with monthly option?

**Comment by mxosman** [comment]
> So, does that mean that if the metric only has ANNUAL frequency datapoints they must be filtered only by annual options based on different starting months; and if it only has MONTHLY datapoints they must be only filtered with monthly option?

Oo - excellent question! I think you're spot on - but let me clarify incase I misunderstood!

If there is only one unique set of frequencies, then I recommend not showing a dropdown at all. This applies for when datapoints are _only_ ALL monthly or _only_ ALL annually (with the same `starting_month`).

For annual frequency, if there are datapoints with different `starting_month`s, then we want to show a dropdown that lets users filter between the different types of annual frequencies.

**Comment by nasaownsky** [comment]
@mxosman So digging more through code and visual representation I see that in "Explore Data" tab there are only datapoints with either `ANNUAL` or `MONTHLY` frequencies. Moreover, those that have an annual frequency always have the same starting month. Is this just problem with the amount and shape of the data showed in staging, or the data gets filtered out somewhere this way and I should change that? If the second is true, then maybe you know where is exactly this filtering method? 

Thank you for your dedication and help in clarifying this subject to me, it is much tougher that I thought!
