### ISSUE TITLE
[Publisher] Allow users to select starting month when creating an annual record

### ISSUE THREAD

**Issue by mxosman** [Recidiviz/justice-counts#1379]
Currently, on the `/records` page, users are able to click on `+ New Record` and create a monthly or annual record. Monthly records require month + year inputs, whereas, Annual records requires either Calendar Year or Fiscal Year + year inputs. We want to allow users to be able to input a starting month for Annual frequency records and have a selection flow similar to the Metric Settings frequency (example screenshot below).

![Screenshot 2024-06-11 at 3 18 03 PM](https://github.com/Recidiviz/justice-counts/assets/59492998/8604d80a-07e2-458d-8709-44e053426125)

Relevant file: `src/components/Reports/CreateReport.tsx` and potentially `src/components/MetricsConfiguration/MetricAvailability.tsx`

The backend should be able to handle this out of the box. It's just a matter of setting the right value for `annualStartingMonth` for annual frequencies. 

This is a very old component - apologies in advance for how unwieldy it might be. Here are some things that may/may not be helpful:
https://github.com/Recidiviz/justice-counts/blob/eb6bb4f75ab9585f044bb64d0802e1806e1b334e/publisher/src/components/Reports/CreateReport.tsx#L68-L74

* This is where the form properties and values are initialized

https://github.com/Recidiviz/justice-counts/blob/eb6bb4f75ab9585f044bb64d0802e1806e1b334e/publisher/src/components/Reports/CreateReport.tsx#L110-L118
* Note that the `month` property will choose `annualStartMonth` to send as a payload when it's an "ANNUAL" frequency. So, for the purposes of the monthly selection dropdown, its options just need to update the `annualStartMonth` property on the form object.

https://github.com/Recidiviz/justice-counts/blob/eb6bb4f75ab9585f044bb64d0802e1806e1b334e/publisher/src/components/MetricsConfiguration/MetricAvailability.tsx#L525-L611

* These are lines of interest in the MetricAvailability page that might be reusable - totally OK to use the new dropdowns on this pager if that's easier - we'll need to update the old ones anyway! (I just wouldn't mix old and new if that makes sense - either replace all dropdowns or keep the old dropdowns.)

Let me know if you have any questions at all!

**Comment by nasaownsky** [comment]
@mxosman is there a figma mockup for this?

**Comment by mxosman** [comment]
Hi @nasaownsky! Unfortunately there isn't, but here's a quick sketch I put together of this change:

![Screenshot 2024-07-01 at 9 16 38 AM](https://github.com/Recidiviz/justice-counts/assets/59492998/53000c78-92fe-44fd-8759-37d9faaf3be4)

Don't worry about matching the design precisely! Let me know if this helps!
