### ISSUE TITLE
[Publisher] Add "Complete" Button to Metric Configuration Pages

### ISSUE THREAD

**Issue by nichelle-hall** [Recidiviz/justice-counts#1412]
**Feature Summary**
The current onboarding process lacks clear indicators of progress, making it challenging to ensure that all data points are configured correctly.

**Suggested Fix**
Add a "complete" button to the metric configuration pages in Publisher. This button will help users understand their progress in onboarding and ensure that all configurations are correctly set up for the shared data points. It should be available anywhere there’s an includes/excludes list, allowing agencies to indicate if the work is completed. Additionally, consider adding similar functionality for turning breakdowns on/off.

**Comment by brandon-hills** [comment]
@nichelle-hall @mxosman @lilidworkin 
Sorry if I'm throwing ideas around too late into this conversation! Feel free to ignore if this has already been discussed. 

But I'm wondering how granular this configuration status needs to be. 

Does CSG feel strongly about the boolean needing to be at the breakdown-level? Could it instead suffice to have one configuration status for the entire MetricSetting?
I'm worried about adding too many new fields to the Metric Interface that ultimately go unused.

I'm also imagining that having the status boolean be at a higher level would also open up a nice view on this page:
<img width="561" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVVZQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ccc42582814f41199cdae120f1ef39802f19a942/Screenshot%202024-07-29%20at%201.24.17%E2%80%AFPM.png" alt="Screenshot 2024-07-29 at 1.24.17 PM.png" />

Where we can categorize each setting as to whether configuration is complete or not

**Comment by lilidworkin** [comment]
@brandon-hills I actually think they really do want it to be at the breakdown level, unfortunately. Can you explain more about your concern? I think these fields will be used by CSG, in that they want to be able to know exactly which parts of the metric have been configured.
