### ISSUE TITLE
[Publisher] [Bug] Users being deleted incorrectly in Admin Panel

### ISSUE THREAD

**Issue by nichelle-hall** [Recidiviz/justice-counts#1423]
While working on an Admin Panel feature, I ran into a bug where I noticed the FE was not sending the correct list of users to update and as a result the BE was deleting users erroneously from the agency. [This Loom ](https://www.loom.com/share/69fd26dff8c0483e9ecbaec8adf1890c) contains the full explanation.

**Comment by lilidworkin** [comment]
We think this was just caused because of the User 0 issue, right? Closing, but let me know if I should reopen!
