### ISSUE TITLE
[Agency Dashboard] Add agency information to public endpoint

### ISSUE THREAD

**Issue by terryttsai** [Recidiviz/justice-counts#151]
Add an agency section to the public endpoint `published_data` and include the agency name and system in it

**Comment by terryttsai** [comment]
Not started, perhaps I should make this high priority?

**Comment by lilidworkin** [comment]
If we need it for the MVP then yes it should be high priority!

**Comment by terryttsai** [comment]
Completed with https://github.com/Recidiviz/recidiviz-data/pull/17142
