### ISSUE TITLE
[Publisher] Bulk Upload/Publish Review: Order the list of records in the left side panel in ascending order

### ISSUE THREAD

**Issue by mxosman** [Recidiviz/justice-counts#1542]
Currently in the review page after a bulk upload the left-side panel that displays the records shows them in random order. We'd like for them to be displayed in ascending order (oldest records -> newest records). If we haven't done so already, we should also make sure that records list in the publish review pages are ordered the same.

![Image](https://github.com/user-attachments/assets/024adfbe-1d1c-482f-944d-d0a8b96ecdfb)

**Comment by mxosman** [comment]
> Hi [@mxosman](https://github.com/mxosman)! Maybe you have some filled file for bulk upload so I could properly test this? I would appreciate if you could share it with me, thank you!

Ah - sorry about that! Here's a link to the spreadsheet: https://docs.google.com/spreadsheets/d/1zEfm5Lecia0L_3IqoDqNT36WgrZSav22/edit?gid=251836306#gid=251836306

LMK if you have trouble accessing it!

**Comment by nasaownsky** [comment]
Yeah, can't access it! Could you please attach it here or send me invite to `nasaownsky@gmail.com`?

**Comment by nasaownsky** [comment]
Lovely, thank you!
