### ISSUE TITLE
[Publisher][Metric Settings] Supervision sectors: Update Revocations metric definitions checkboxes to behave as radio inputs (only allowing one selection) for a new definition prompt) 

### ISSUE THREAD

**Issue by mxosman** [Recidiviz/justice-counts#1602]
For Supervision sectors, the Revocations metric definition (see below screenshot) will have a new set of questions:

Prompt: If reporting breakdowns for the Revocations metric, please select what your data represents:

Choices:
* Data reflects the most recent violation type
* Data reflects the most serious violation type in a person’s supervision term

Reference definition that will be updated: 
![Image](https://github.com/user-attachments/assets/30e177a5-28be-4d46-90c8-d32d5d93396f)

The backend will add this new question with the following `description` property as the "key": `"Revocation metric data type"`

We need to update the checkbox behavior to allow the user to _only_ select one or the other and not both - this behavior _only_ applies to this question for this metric definition, so we'll need to update the logic to listen for the above `description` key in the `includes_excludes` property and adjust its behavior to allow the user to only choose one of the options.

This will be hacky and gnarly, but the only way I can think of currently to satisfy this new requirement for these new sets of questions. Let me know if anything feels confusing or where I can clarify further! @nichelle-hall will update the backend to send these new definition questions to the FE, so most of it should work automatically out of the box - it's just the behavior of the checkboxes that need to adjust for just this new question.

**Comment by nichelle-hall** [comment]
Hi @nasaownsky,

I wanted to give you a heads-up about some API changes related to the new Supervision Revocations includes/excludes functionality. Here's a summary of the changes:

**`check_all_that_apply` Field:**
A new `check_all_that_apply` field has been added to the includes/excludes response. It indicates whether checkboxes should be rendered as non-exclusive (true) or exclusive (false). For existing includes/excludes sets, this defaults to `true` to maintain current behavior.

**New Supervision Revocations Includes/Excludes:**
The Supervision Revocations metric introduces two separate includes/excludes sets. For this metric:

The first set has `check_all_that_apply` set to false, as it involves exclusive checkboxes (users can select only one option at a time).
The second set behaves as existing includes/excludes do, with check_all_that_apply set to true.

Example Response:

```
[
    {
        "check_all_that_apply": false,
        "description": null,
        "settings": [
            {
                "default": "Yes",
                "included": null,
                "key": "REFLECTS",
                "label": "Data reflects the most recent violation type"
            },
            {
                "default": "Yes",
                "included": null,
                "key": "DOES_NOT_REFLECT",
                "label": "Data reflects the most serious violation type in a person’s supervision term"
            }
        ]
    },
    {
        "check_all_that_apply": true,
        "description": null,
        "settings": [
            {
                "default": "Yes",
                "included": null,
                "key": "PRISON",
                "label": "Revocation to prison"
            },
            ...
        ]
    }
]
```

This is still a work in progress, but if you’d like to start exploring or testing the changes, you can check out the branch `nichelle-hall/revocations-supervision-changes`.

Let me know if you have any questions or need more details!

**Comment by mxosman** [comment]
Hi @nasaownsky! Can I ask you to prioritize this one now that the BE has been merged in? The `check_all_that_apply` field has now been renamed to `multiselect`.

**Comment by nichelle-hall** [comment]
I've updated my original message to reflect the name change.

**Comment by nasaownsky** [comment]
Hi @mxosman @nichelle-hall! Thank you all for your clarifications and updates, much appreciate! Will get to work on this task.

**Comment by mxosman** [comment]
@nichelle-hall - after reviewing Ilya's PR - I'm not sure if the `REFLECTS` / `DOES_NOT_REFLECT` makes sense as keys for these options:

* Data reflects the most recent violation type
* Data reflects the most serious violation type in a person’s supervision term

None of them specify not reflecting something, but rather one of them reflects the most recent and the other the most serious. I think it might be worth updating these keys to avoid confusion if we need to surface this data.

**Comment by nichelle-hall** [comment]
> [@nichelle-hall](https://github.com/nichelle-hall) - after reviewing Ilya's PR - I'm not sure if the `REFLECTS` / `DOES_NOT_REFLECT` makes sense as keys for these options:
> 
> * Data reflects the most recent violation type
> * Data reflects the most serious violation type in a person’s supervision term
> 
> None of them specify not reflecting something, but rather one of them reflects the most recent and the other the most serious. I think it might be worth updating these keys to avoid confusion if we need to surface this data. LMK your thoughts!

SUCH a good point! I missed this! I'll put up a fix now.
