### ISSUE TITLE
[Agency Dashboard] Select Metrics mobile modal

### ISSUE THREAD

**Issue by terryttsai** [Recidiviz/justice-counts#206]
![Screen Shot 2022-12-06 at 2.14.37 PM.png](https://images.zenhubusercontent.com/623bb0d443429e7fa7d03621/43c42555-29e9-44d0-9827-6c34f5a838a7)

Render a full-screen modal when clicking the select metrics mobile button, selecting a metric closes the modal.

**Comment by lilidworkin** [comment]
@terryttsai is the non-mobile version of the Select Metrics dropdown done?

**Comment by terryttsai** [comment]
Yes!
