### ISSUE TITLE
[Agency Dashboard] Mobile filters modal

### ISSUE THREAD

**Issue by terryttsai** [Recidiviz/justice-counts#207]
![Screen Shot 2022-12-06 at 2.15.31 PM.png](https://images.zenhubusercontent.com/623bb0d443429e7fa7d03621/b9b10877-d246-42e9-9eb2-1c0a029f93ff)

Add a mobile filters button. Clicking on the mobile filters button should render a full-screen modal to adjust filter settings.

**Comment by lilidworkin** [comment]
@terryttsai are the filters/dropdowns for non-mobile finished and implemented as per the most recent designs?

**Comment by terryttsai** [comment]
Yes, non-mobile is complete.

**Comment by terryttsai** [comment]
With the exception of the month / year toggle

**Comment by terryttsai** [comment]
https://github.com/Recidiviz/justice-counts/issues/183
