### ISSUE TITLE
[Frontend][Publisher][Clean Up] Metric Configuration: Move all onChange/onClick logic from the render

### ISSUE THREAD

**Issue by mxosman** [Recidiviz/justice-counts#221]
There's a lot of logic within the renders of the metric configuration component which can be cleaned up into handler functions that could live outside the render.

Example: the logic in the `onChange` could be moved into something like a `handleSelection` function w/ the appropriate parameters.

![Screenshot 2023-01-04 at 11.21.33 AM.png](https://images.zenhubusercontent.com/6215b87f9009a13a581784dd/1e9e6f86-1cbe-49e6-a794-c60af420abee)

Here are the files that could use this clean up:

**MetricConfiguration** >
  * Configuration.tsx
  * ContextConfiguration.tsx
  * MetricDefinitions.tsx
  * RaceEthnicitiesForm.tsx

**Comment by lilidworkin** [comment]
Another refactor task for you @ivan-kishko. @mxosman can also be point of contact
