### ISSUE TITLE
[Frontend][Common] Refactor Toast Component

### ISSUE THREAD

**Issue by mxosman** [Recidiviz/justice-counts#235]
The toast component that we use throughout Publisher is in sore need of a clean up refactor. It should have the same functionality, but instead of accepting 6 parameters, we can pass in something like an `options` object that will store all of the properties needed (along with setting defaults where appropriate).

This was originally implemented in vanilla JS (in haste) but does not need to be if there's a better implementation. The only thing we have to keep in mind is this function can be called from anywhere within the app and not exclusively in rendered components (e.g. you can call this within a function inside of a data store).

I haven't explored this yet - but I wondered if [React Portal](https://reactjs.org/docs/portals.html) would be a better option. It might not be if we want to have the flexibility of calling this from anywhere in the app.

**Comment by lilidworkin** [comment]
@ivan-kishko , this is something for you to tackle next while we wait on updated designs! @mxosman can be your point of contact
