### ISSUE TITLE
Modify permissions for Agency Settings page

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#240]
Previously I asked @ivan-kishko to hide the Agency Settings page for everyone unless they had RECIDIVIZ_ADMIN permissions. I was wrong about this. We want to always show the page, BUT we want to hide certain sections from non-admins. The logic should be:

* Everyone can see the Agency Settings page in the Navigation and can load this page
* Everyone can see the Basic Information section
* All Supervision agencies can see the Supervision Populations section
* Recidiviz Admins only can see the Team Management section
* Recidiviz Admins only can see the Jurisdictions section

Sorry about this change. Thank you!!

**Comment by terryttsai** [comment]
Should non-admins still be able to see who else is on their team?
