### ISSUE TITLE
Send request to /users [PATCH] to invite user to agency

### ISSUE THREAD

**Issue by nichelle-hall** [Recidiviz/justice-counts#289]
The backend now supports inviting a user to an agency!

Send a PATCH request to `api/users` with a request body that contains the `agency_id` (of the current agency), `invite_email`, and `invite_name` when the `Invite` button is clicked. 

<img width="929" alt="Screen Shot 2023-01-11 at 1 18 52 PM" src="https://user-images.githubusercontent.com/19961693/211898053-edfb71f0-718e-4ae6-9f80-8f4a519ca3d8.png">

When the request is sent, add the user to the team list with an `Invited Badge`. The user details should also be greyed out. Full designs [here](https://www.figma.com/file/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?node-id=6255%3A15227&t=VwEmEiGrp5wtgb08-0).

**Comment by ivan-kishko** [comment]
Hello there @nichelle-hall!) Nice to meet You! One question - is there any validation happening on a backend side? Or regardless of this I should add user to list right after request is sent and not wait until name/email are checked and user is added to team list in "agency.team"?

**Comment by nichelle-hall** [comment]
> Hello there @nichelle-hall!) Nice to meet You! One question - is there any validation happening on a backend side (like should email contain "@" or name should be longer than 2 letters or smth like that)? Or regardless of this I should add user to list right after request is sent and not wait until name/email are checked and user is added to team list in "agency.team"? AND is it PUT or PATCH, cause in task name it is put and in description it is patch

1) There is no validation happening in the backend for email. If you could add that validation in the FE, that would be awesome!
2) So this question is interesting. This endpoint doesnt send a response body. I plan on retuning `invitation_status` back on in the response body for `/users` GET. 
3) It's PATCH! Just updated the ticket title.

**Comment by nichelle-hall** [comment]
How to test manually.

1. Toggle to an agency of your choice, add a new name and email to the invite text boxes. Click invite.
2. Check the email you provided, there should be an email inviting you to the publisher.
3. Create an account with that name and email, you should only be able to see the agency you were invited to. 


1. In the first account, toggle to a **different** agency of your choice. Add the **same** name and email you invited earlier, Click invite.
2. Check the email you provided, there should be an email inviting you to the publisher.
3. Sign in with that name and email. You should already have an account. You should now be able to access **two** agencies.
