### ISSUE TITLE
Github Action for running frontend tests on every PR

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#3]
Base on https://github.com/Recidiviz/recidiviz-data/blob/main/.github/workflows/ci.yml

**Comment by mxosman** [comment]
I can work on this as we'll be needing it soon. 😄

**Comment by lilidworkin** [comment]
That would be awesome! cc @terryttsai -- why don't you guys coordinate and figure out who does what?

**Comment by terryttsai** [comment]
Awesome!
