### ISSUE TITLE
[Backend] Duplicate Datapoints in Data Upload API upload response

### ISSUE THREAD

**Issue by terryttsai** [Recidiviz/justice-counts#31]
Lili noticed that the count of overwrites don't add up correctly, and when I dug into this, I found that sometimes we receive duplicate datapoints in the `datapoints` array in the Data Upload API response.

One example of this is when uploading the [prison_warnings](https://docs.google.com/spreadsheets/d/1_3RlaBz78dpqW6VcJgG2F-ZmGIJTwsQ3/edit#gid=720379711) sheet,  under Admissions you see 39 overwrites instead of 26 (or some other numbers).

I see that all the aggregate values are given twice.

![Screen Shot 2022-09-20 at 4.31.15 PM.png](https://images.zenhubusercontent.com/623bb0d443429e7fa7d03621/5e559a82-4105-438e-a533-2010bdcc88cf)

**Comment by lilidworkin** [comment]
Thank you SO much for writing up this super detailed issue, @terryttsai !
