### ISSUE TITLE
Updated designs for Agency Settings

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/justice-counts#320]
We've made a few updates to the designs of the Agency Settings page that address many of the comments in #264. These are reflected in [Figma](https://www.figma.com/file/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?node-id=6508%3A16190&t=izfZRan3k3To7w10-0). 

Changes are summarized below. CC @lilidworkin @agronomic : 

### General
- EditMode should now open a modal to edit the section. (This avoids some of the previous confusion of what to do when the user tries to edit another section). 
- Team Management has moved to a new page, separate from the rest of Agency Settings. 
- [New modal](https://www.figma.com/file/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?node-id=6688%3A16637&t=izfZRan3k3To7w10-0) for cancelling unsaved changes. Should activate upon: 
    - Clicking Cancel
    - Clicking outside the editMode modal. (If this is still complicated, skip.)
- Copy adjustments throughout. 

### Agency Information 
No major changes. 

### Supervision Populations
- In ReadMode, the options (Parole, Probation, etc) should be filtered to only the ones that have been selected. 
- There should no longer be checkmarks next to the selected options in ReadMode. 

### Jurisdictions
- Updated design for the search box options (includes a little (+) sign and a heavier drop shadow). 
- Exclusions flow has been properly defined in the mocks. 

### Team Management 
Again, note that this is now on a separate page (still within Agency Settings). 
- New table 
- New interaction to remove people, grant/remove admin status, etc. Note doing any of these actions should also activate a "toast" message: 
    - "[NAME] has been invited to your agency." 
    - "[NAME] has been removed from your agency." 
    - "[NAME] has been promoted to an admin." 
    - "[NAME]'s admin status has been removed." 
- Invite users flow should check if the email is valid. 

Note that we are still waiting for a few small things from @agronomic : 
- Empty states for each section

**Comment by ivan-kishko** [comment]
Hello there!) I believe r4 is design that described here, right @hobuobi?
