### ISSUE TITLE
Tweaks to "Technical Definitions are not available for this metric yet." logic

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#336]
After playing around a bit, I came up with a few ideas to make this a bit clearer -- lmk what you think and if this is easy to implement! 

**Case 1: Top-level metric does not have any includes/excludes defined.**
We should show "Technical Definitions are not available for this metric yet." (I believe this is the current behavior already!)

**Case 2: Dimension does not have any includes/excludes define, BUT it does have at least one context (i.e. all Other dimensions will fall in this category).**
We should _not_ show the "Technical Definitions are not available for this metric yet.", and should just show the text box. This will require a small change -- currently it looks like this:

![Screenshot 2023-01-25 at 9.32.30 AM.png](https://images.zenhubusercontent.com/620e7d8c0c5fad82d897844d/a41228e7-ad86-4d38-ab5c-28ed5eb4d367)

**Case 3: Dimension does not have any includes/excludes define, and doesn't have a context either (all Unknown dimensions will fall in this category).**
We should say ""There are no technical definitions for this breakdown." instead of  "Technical Definitions are not available for this metric yet." This will require a small change.

**Comment by mxosman** [comment]
Thank you for the super helpful description and the way you broke apart the 3 cases! Everything is crystal clear!

**Comment by mxosman** [comment]
For case #2 - I'm thinking this should apply to top level metrics that have at least one context as well, right? Meaning - we should removing the "Technical Definitions are not available for this metric yet." if there's one/more context boxes?

Example:

<img width="1386" alt="Screenshot 2023-01-26 at 11 23 51 AM" src="https://user-images.githubusercontent.com/59492998/214890980-56620bb4-40d0-4fdb-b393-d57d8efbd046.png">
