### ISSUE TITLE
Remove "Context" header from Metric Config right sidebar

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#337]
Currently, the right sidebar for a top-level metric looks like this:

![Screenshot 2023-01-25 at 9.34.17 AM.png](https://images.zenhubusercontent.com/620e7d8c0c5fad82d897844d/b35f5223-5750-46b9-a839-02db88c86699)

Whereas the right side bar for a dimension looks like this (no Context header or divider line):
![Screenshot 2023-01-25 at 9.34.34 AM.png](https://images.zenhubusercontent.com/620e7d8c0c5fad82d897844d/08365609-0a17-41df-8bc6-dcebbaaee494)

I like the second version better -- can we make the top level metric look like that?

**Comment by mxosman** [comment]
Absolutely! I agree 100%!
