### ISSUE TITLE
[Frontend][Publisher] Fix no starting month selection for an annual metric

### ISSUE THREAD

**Issue by terryttsai** [Recidiviz/justice-counts#353]
![Screen Shot 2023-01-30 at 12.14.31 PM.png](https://images.zenhubusercontent.com/623bb0d443429e7fa7d03621/fa9d094d-b59a-491d-98ee-61e9cc7bf7a1)

Seen in https://justice-counts-web-qqec6jbn6a-uc.a.run.app/agency/168/settings/metric-config?system=supervision&metric=supervision_budget

**Comment by lilidworkin** [comment]
Going to assign this to @mxosman !
