### ISSUE TITLE
[Frontend][Publisher] Small refactor to the Supervision tab names

### ISSUE THREAD

**Issue by mxosman** [Recidiviz/justice-counts#356]
A given Supervision agency can oversee both Prisons and Supervisions. Supervisions can then be broken down into Parole, Probation, Pretrial, and Other.
 
Currently in the Metric Configuration page, these 6 categories are shown in a 'flat' row. To distinguish this hierarchy, we want to implement a quick fix and rename this tabs as follows:
Prisons, Supervisions: Combined,  Supervisions: Parole,  Supervisions: Probation,  Supervisions: Pretrial,  Supervisions: Other

![](https://paper-attachments.dropboxusercontent.com/s_A313308A9742EC9A5E19E1EAA5C7C017CFE366474AB9B0647BCE9C98EB35BEB2_1675110125412_Screenshot+2023-01-30+at+2.22.01+PM.png)

**Comment by lilidworkin** [comment]
Thanks for filing @morden35  / @mxosman ! It's possible that (assuming we want to do this) the right way to do it would be on the backend ... so let's discuss before anyone gets started on it!

**Comment by mxosman** [comment]
Sounds great! I'll move this to the bottom of the priority list and let you know before I start working on it!

**Comment by lilidworkin** [comment]
@mxosman so if we want to do this on the backend, I think this is how:

We'd be making a change [here](https://github.com/Recidiviz/recidiviz-data/blob/89420be3f33cfa0e05c37cf888bd04ccdc68ea50/recidiviz/persistence/database/schema/justice_counts/schema.py#L287). Instead of

```
            "systems": [
                system_enum.value
                for system_enum in System.sort(
                    systems=[System(system_str) for system_str in (self.systems or [])]
                )
            ],
```

it would be something like this:

```
system_name_to_display_name: {
   "Supervision": "Supervision: Combined", # or whatever Humphrey wants
   "Parole": "Supervision: Parole", 
    # etc
}

system_names = []
for system_enum in System.sort(systems=[System(system_str) for system_str in (self.systems or [])]):
    if system_enum.value in system_name_to_display_name:
        system_display_name = system_name_to_display_name[system_enum.value]
        system_names.append(system_display_name)
   else:
        system_name.append(system_enum.value)
```

**Comment by mxosman** [comment]
Thank you so much for this, Lili! Looking forward to diving in to this!

**Comment by mxosman** [comment]
So here are the changes in the backend to replace the Supervision system name to `Supervision (Combined)`:
```
    def to_json(self) -> Dict[str, Any]:
        system_name_to_display_name = {
            "SUPERVISION": "Supervision (Combined)", # should this 
        }
        system_names = []
        for system_enum in System.sort(systems=[System(system_str) for system_str in (self.systems or [])]):
            if system_enum.value in system_name_to_display_name:
                system_display_name = system_name_to_display_name[system_enum.value]
                system_names.append(system_display_name)
            else:
                system_names.append(system_enum.value)

        return {
            "id": self.id,
            "name": self.name,
            "systems": system_names,
            ...
            ...
```

Here are a brain-dump of what I'm thinking:

* The above change will replace the "SUPERVISION" system name to "Supervision (Combined)" and include it in the `systems` property of the JSON as `systems: ["Supervision (Combined)", "PAROLE", "PROBATION", ...]`
  * Q: Instead of "Supervision (Combined)" should be in a similar structure to other system names (e.g. "SUPERVISION_COMBINED")? If we go with the former - that might be tricky for the `system` param in the URL - we'll have to remove the space. If we go with the latter - we'll have to transform it any way to get it to appear as "Supervision (Combined)"
* The FE will need to make changes to all areas where it is expecting the string "SUPERVISION"
  * Update `AgencySystems` type in `justice-counts/common/types.ts` 
    * Do we replace "SUPERVISION" with "Supervision (Combined)" (or "SUPERVISION_COMBINED" if we choose this to be the name the backend sends)?
  * Update `SupervisionSystem` const in `justice-counts/common/types.ts` similar to above
  * Update `isAgencySupervision` getter in `justice-counts/publisher/src/stores/AgencyStore.ts`
* Here are some of the FE components that I can think of that display the system name:
   * DataEntryForm (Report Summary Panel)
   * MetricsView (Data Viz)
   * MetricConfiguration (the multi-system tabs)
   * Uploaded Files
   * Agency Settings
* The bandaid for a FE only solution is to go around and add this conditional to check 2 things:
  1. if it is a Supervision system
  2. if it has subsystems
```
  const hasSupervisionWithSubsystems =
    currentAgency &&
    currentAgency.systems?.includes("SUPERVISION") &&
    currentAgency.systems.length > 1 &&
    currentAgency.systems.filter((system) =>
      SupervisionSubsystems.includes(system)
    ).length > 0;
```
   * Then, I transform whatever system name is being rendered by checking if the name is "SUPERVISION" and if it has subsystems - if so, render it as "Supervision (Combined)" -- otherwise, render the system name as usual.

I think either way we'll have to adjust both FE & BE to make this happen - I'm still thinking through this and trying to figure out the best long-term approach to make this update.

**Comment by lilidworkin** [comment]
@mxosman thanks so much for thinking through this so carefully and explaining your thoughts so well! This was insanely helpful. You're entirely right in your analysis -- changing it on the BE isn't nearly as simple as I thought. Looking at things now, I suspect it might be easiest to change it on the frontend, and essentially do the check you suggested above, whenever we are rendering the system name. Currently, whenever we render a system's name, it seems like we call one of two util methods first -- either removeSnakeCase or normalizeSystem. So we should probably condense these into one helper function, and then have that helper function also do the check to decide if it should change Supervision to Supervision (Combined). I actually don't think we need to touch the backend at all. The only thing is we have to remember to call this helper whenever we render a system's name, but since we were already calling helpers for that, it seems fine to me! Sorry for leading you down the wrong path re: doing this on the backend!

**Comment by mxosman** [comment]
> ! This was insanely helpful. You're entirely right in your analysis -- changing it on the BE isn't nearly as simple as I thought. Looking at things now, I suspect it might be easiest to change it on the frontend, and essentially do the check you suggested above, whenever we are rendering the system name. Currently, whenever we render a system's name, it seems like we call one of two util

Thank you so much for your feedback, Lili (and for parsing through my ramblings)! No apologies necessary at all! This was a great exercise and great continued exposure to the BE! Such a great idea to create/consolidate the helper utils since we already do some sort of formatting for the system names - that will make it feel much less hack-y - and good practice in general! 

Thank you so much for working with me on this one - and for the great ideas to solve on the FE!  🙌
