### ISSUE TITLE
Improve frontend experience for aggregating/disaggregating Supervision metrics

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#358]
See some playtesting feedback:

From Humphrey:
> Might want to provide a little extra explanation about what’s happened – i.e., these metrics will appear under the Parole, Probation, etc. sections on Metric Configuration. 
> Maybe also link out to the other (disaggregated) metrics. 
> When I can’t change the metric availability because of the aggregated/disaggregated setting, I would like a tooltip or something to explain this. 

From Mahmoud:
> Idea for Supervision disaggregations: could we add another badge that says “Disaggregated” or “Combined” in the metric overview list in place of “Inactive” (which we’ll leave for when a metric is actually disabled)? Not sure how feasible this is but just a thought! It might end up being more work to infer this or add additional/move state where we didn’t have before.

@terryttsai up to you what pieces of this you want to address / how to address it! Feel free to discuss with Humphrey.

**Comment by terryttsai** [comment]
Should we consider a sub-tab for supervision disaggregated metrics? Like under Supervision, there's a disaggregated section to break it down by Parole, Probation metrics etc?

**Comment by lilidworkin** [comment]
I personally love that idea @terryttsai ! Might be good to run it by @hobuobi before you spend too much time on it?

**Comment by terryttsai** [comment]
Ran it by Humphrey who says he likes the direction, would want to check in with Juan about it first

**Comment by lilidworkin** [comment]
@terryttsai makes sense to me! If it's easy to do, you could try implementing a couple different options/experiences in the frontend and take screenshots/videos, and then we could discuss as a group? But not worth it if that would take a take of time.

**Comment by mxosman** [comment]
Just looking back through older tickets - I think this one is safe to close as we recently implemented a clearer FE solution and the Publisher audit updates will hopefully enhance this more!

**Comment by lilidworkin** [comment]
Oh great, thanks @mxosman !
