### ISSUE TITLE
Minor branding updates (logo, footer, etc) 

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/justice-counts#369]
In order to meet expectations with the Bureau of Justice Administration (BJA; primary funder for the project), we have to update a few things about how the Justice Counts brand appears throughout the application. Changes are detailed in Figma. 

### P0: Header + Logo

The logo in the top-left should be updated (dark blue background, with a gradient logo). Additionally, the words "Justice Counts" should be added immediately to the right of the logo. (For now, this should not appear at smaller screen sizes, though we might update this in an upcoming ticket on responsiveness.) 

![navbarUpdated](https://user-images.githubusercontent.com/7134733/216440718-b9c906dc-6dbd-4b3f-aeb7-fff4ab0476b6.png)

### P0: Footer 
A footer should be included at the bottom of every page that includes information about the project grant, key organizations, etc. 
- The footer should not be fixed at the bottom of the page (always visible), but rather should appear once the user scrolls through all of the content on the page. Note that this might mean adjusting the positioning of some elements (for example, the note in the bottom-left about Metric Configuration in the Data Entry View). Feel free to discuss different approaches!
- The footer should be generally responsive to the screen size – if more specific guidance has not been given by the time you get to implementing this, feel free to do what is easiest. 

![Group 2823](https://user-images.githubusercontent.com/7134733/216443654-ab0db138-026a-40b3-91e9-127807a4176f.png)

### P1: Auth0 Portal (for @lilidworkin ) 
- The logo (referenced here: https://justice-counts-web-qqec6jbn6a-uc.a.run.app/android-chrome-192x192.png) should be updated to the new gradient logo. 
- The button color should be updated to #001133. 

### P2: UI Colors
#001133 should be used as the base color for UI text, rather than #171C2B. The opacities (e.g., 60% for a lighter gray) used should be consistent with the old implementation. 
- Note that it's possible that the implementation has not defined colors by base color x opacity, in the same way that the design system in Figma does. If that's true and changing the colors would be anything more than a single line change, please skip this.

**Comment by ivan-kishko** [comment]
Hello @hobuobi. What to do with the part where greeting appears?
![Screen Shot 2023-02-06 at 4 23 55 PM](https://user-images.githubusercontent.com/84838278/216982803-bf1ee0c0-cf85-4ebf-b377-f09e641374b0.png)
