### ISSUE TITLE
Responsiveness Refactor

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/justice-counts#389]
This ticket outlines a holistic refactoring of how the Publisher interface responds at different window sizes. The full set of changes is mapped out here: https://www.figma.com/file/C9A2LRkCC2gxGRCvv1FSjr/Responsive-design-for-JC?node-id=16%3A1939&t=mOqyK2lGC6d8gAJk-0

There are a few new breakpoints defined regarding the window width: 

-  **1440px+ (LARGE):** This is what Publisher is currently designed for and works best at.
- **1024px (NORMAL):** This is a more realistic assumption of a user’s screen resolution, as government workers are often using screens with lower resolutions. The application generally fairs well at this screen resolution, but still suffers some issues.
- ~**700px:**This might be useful to users who are trying to multitask (i.e., look at existing reports, queries, etc at the same time that they enter data into Publisher).
- ~**512px (HALF):** This is what the window size would be at *half* of the Normal screen width. 

The designs in Figma are organized to show what different screens would look like at the above screen widths, and cover changes in the following areas of the application: 
- Records
- Settings (including Metric Configuration) 
- Bulk Upload
- Data 

The Figma is the ultimate source of truth for this refactor. To summarize some of the major changes at smaller sizes: 
- Navigation bar collapses to a hamburger menu at smaller sizes and removes the "Learn More" tab in place of the footer. 
- Tabs (such as the ones on the Records Page or the Data Entry View) turn into dropdown menus. 
- The large side menu on the Data Page turns into a dropdown. 
- Font sizes are generally reduced throughout on smaller screens. 

Throughout implementation, please call out if any proposed changes would require a more significant change to existing components or infrastructure.

**Comment by ivan-kishko** [comment]
Hello @hobuobi, @agronomic) I have a couple questions about Data page - 
1. Where are "Switch to table view" and "Go to metric configuration" buttons?
2. How should be displayed dropdown with multiple systems?
3. What is this text below "Avg.Value"?
4. What are these buttons at the bottom of the page, "Share" "Download" and "Learn More", and if "Learn More" is from top navigation why is it only here at data page?
