### ISSUE TITLE
[Frontend/Backend][Bug] Disaggregations appear enabled by default without any dimensions enabled

### ISSUE THREAD

**Issue by mxosman** [Recidiviz/justice-counts#420]
Example: https://justice-counts-web-qqec6jbn6a-uc.a.run.app/agency/161/settings/metric-config?system=jails&metric=jails_total_staff

![Screenshot 2023-02-17 at 2.20.58 PM.png](https://images.zenhubusercontent.com/6215b87f9009a13a581784dd/9ce6c971-62e7-4987-9cb9-24ba6e302b83)

**Comment by lilidworkin** [comment]
@mxosman possibly related to this, but I'm seeing wonky behavior where the dimensions turned on/off in settings don't seem to match the ones turned on/off in the Records page. I need to look into this further and get you a repro, but putting here before I forget.

**Comment by lilidworkin** [comment]
e.g. https://justice-counts-web-qqec6jbn6a-uc.a.run.app/agency/150/records/3392 shows ROR release disabled but that doesn't match settings xhttps://justice-counts-web-qqec6jbn6a-uc.a.run.app/agency/150/settings/metric-config?system=courts_and_pretrial&metric=courts_and_pretrial_pretrial_releases

**Comment by mxosman** [comment]
They are totally related! #428 should have the fix for this as well.
