### ISSUE TITLE
Responsiveness followups [non-design blocking][Part 2]

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#436]
*The ordering of components is incorrect; the contents of the left panel (availability, frequency, breakdowns) should always appear at the top of the screen.
*Also, the breakdown selector is showing up separately from the breakdown options. These should always appear together, one after the other.

From @ivan-kishko (comment [here](https://github.com/Recidiviz/justice-counts/pull/416#issuecomment-1441514513):

> I am not sure but in figma there are notes in metric config design that says explicitly that sidebar content shows first so that is what I did. The example was took from race/ethnicities breakdown so I am not sure if this is true only for Race/ethnicities or not but this note (Whichever breakdown type user selects, the content that shows up usually in sidebar area should show up here.) made me think that this ordering is true for whatever breakdown user selects

**Comment by kchony** [comment]
Hi @lilidworkin @ivan-kishko I outlined the [clarification here in Figma](url)

**Comment by kchony** [comment]
<img width="261" alt="Screen Shot 2023-02-27 at 11 22 32 AM" src="https://user-images.githubusercontent.com/126192298/221662446-f0d99bae-6958-4757-a9cf-f8d1d0f1b96e.png">

Updated in Figma and above here.

**Comment by ivan-kishko** [comment]
@kchony I think what you showing here inside dropdown are dimensions, while dropdown is responsible for choosing disaggregation (tabs in wide view). So this table which I pointed out are dimensions of disaggregation and it is not anywhere in metric config edits in figma. @lilidworkin @hobuobi I might be wrong or missing something so please correct me if I am wrong. Thanks!

**Comment by hobuobi** [comment]
Definitely not wrong – I think the designs are only accounting for dimensions/breakdown categories, like you're saying. We would need some way to switch the breakdown/disaggregation. 
Noting that we'll probably update this page soon, I don't want us to overthink this. If adding another dropdown accomplishes this, I'm fine with it.

I'm also fine with using the dropdown only for the breakdowns/disaggregations, and showing the list items below that – seems more consistent?
