### ISSUE TITLE
Responsiveness followups [General][Design Blocking]

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#437]
* Titles are generally very small, and it’s a little off-putting / makes it easy to lose where you are. I would recommend making these larger!
* Feeling like the app is defaulting to the smaller setting a little too quickly, resulting in very vertical layouts with little padding. The breakpoint might actually be fine (would have Kristen address), but maybe there should be some padding on either side of the main content, rather than extending all the content to the edges of the screen.
* Regarding the Tabs -> Dropdown treatment:
     * The triangles are a little clunky in practice. Would visually refine these (maybe they just need to be smaller?)
     * In general, I’m a little less confident about this seeing it in practice; I’m not liking how this treatment makes it such that you might not know that certain options (e.g. breakdowns) exist without clicking the item.

**Comment by kchony** [comment]
Bullet #1: We can make the titles larger. Right now it's 12pt, but we can change to medium 18pt font. We don't want to make it too big bc it's actually serving as a breadcrumbs navigation.

Bullet #2: I added another break point bc i think the web app could get value from it (~860px) and [it's outlined here. ](https://www.figma.com/file/C9A2LRkCC2gxGRCvv1FSjr/Responsive-design-for-JC?node-id=16%3A1939&t=aLdYFHIf6SwMH4dR-1)

Bullet #3: Agreed that triangles could be smaller. @hobuobi i Regarding metric configuration interactions, are you ok with these being like these for now until we make bigger changes with the next rev of metric configuration? I agree that the interactions are funky, but I was trying to work with what was already implemented :sweat_smile: We can weave responsive designs with the next version too.
