### ISSUE TITLE
Responsiveness followups [Team Management][Design Blocking]

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#439]
* Biggest problem is the “Invite” input fields, which are very large and unnecessarily wide. I would:
     * Adjust the font size.
     * Place these next fields and the invite button next to one another horizontally until the fields become too small.

**Comment by kchony** [comment]
I think in general we should add another breakpoint at around ~860px per @hobuobi's feedback on app defaulting to smaller setting too quickly.

Agree with @lilidworkin and outlined the suggestion

In general contents of team management should remain the same until 860px breakpoint (this is also when padding on both sides is 24px). Then from 859px to 512px, it should look like the second image below.

Also, input field and button dimension should remain the same until 512px breakpoint and should look like the second image below.

<img width="570" alt="Screen Shot 2023-02-23 at 8 16 37 PM" src="https://user-images.githubusercontent.com/126192298/221090519-f561ed74-6743-405f-a65f-2295562e498a.png">
s below:

<img width="354" alt="Screen Shot 2023-02-23 at 8 16 40 PM" src="https://user-images.githubusercontent.com/126192298/221090611-39eae8b6-e647-46cf-8e31-b87259b348f7.png">
