### ISSUE TITLE
Bulk publishing/unpublishing

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#484]
Figma designs [here](https://www.figma.com/file/brkAAatBCcvSnLJOIxZJIM/recidiviz-x-allison?t=GTW5xHS8CHQTSxA7-0)
PRD [here](https://www.notion.so/recidiviz/Bulk-Publishing-e01f3a4216bd4a59907bc3bc004d7baf)

Goal is to support two main flows:
1) From Records page: Hit Bulk Publish, see Review Page, then publish and confirm (all new)
2) From Bulk Upload: See Review Page (already exists but needs to be redesigned), be able to publish from this page (new), show relevant warnings when publishing (new)

Components to this project:

1. Records page redesign (aesthetic only); task for Ivan [here](https://app.zenhub.com/workspaces/justice-counts--622109ea3bb6e0001d2d06ad/issues/gh/recidiviz/justice-counts/478)
2. Review page redesign (aesthetic only); task for Ivan [here](https://app.zenhub.com/workspaces/justice-counts--622109ea3bb6e0001d2d06ad/issues/gh/recidiviz/justice-counts/481)
3. [Medium] New backend API endpoint for publishing or unpublishing multiple records at once
4. [Easy] Show a modal before Bulk Unpublishing
5. [Large] Show the review page after Bulk Publishing (doesn't need to be the redesigned review page, so this doesn't necessarily have to block on step 2).
    * Update backend response to include list of modified reports
6. [Large] We already show the review page after Bulk Upload. But, currently it's not possible to publish from that Review Page. So we need to make it possible to Publish from the Review page when it appears after Bulk Upload, but show relevant warnings. We want to warn users when other Records will be affected by saving the data as a draft or publishing that were not part of the uploaded data. This happens because all uploaded data goes into Records, which may contain other metrics. This falls into two main edge cases that we must solve for:
* Save as Draft: Warn the user if there is preexisting published data in time ranges represented by the uploaded data that would then be unpublished if the user continues.
* Publish: Warn the user if there is preexisting draft data in time ranges represented by the uploaded data that would then be published if the user continues.

Extra credit: Don't allow records with validation errors to be bulk published

**Comment by lilidworkin** [comment]
cc @morden35  -- @mxosman , @morden35 and I were chatting and she is up for helping out with the backend pieces of this if it would be helpful! Even just to bounce ideas off of or help with code review, etc

**Comment by mxosman** [comment]
Sounds great! Thank you so much, @morden35!

**Comment by morden35** [comment]
> Sounds great! Thank you so much, @morden35!

You are very welcome! Feel free to ping me whenever you get around to this!

**Comment by lilidworkin** [comment]
Three flows:

Endpoints:
* Update multiple report statuses [DONE]
* Get reports by id
     * Need to update to return datapoints for each report
     * Currently return metrics for each report -- I think we no longer have to do this, we can just return the datapoints model
* /spreadsheets POST Bulk upload response
     * Need to update to return both created and updated report ID

* Single report --> Publish: DONE!
    * Make loading of the Review page more efficient (don't need to load all datapoints for the agency) (?)
* Records page --> Publish
    * Make loading of the Review page more efficient (don't need to load all datapoints for the agency). **Replace this with get reports by ID endpoint.**
   * From Review page --> click Publish, what actually happens? Do all Reports get published? Should use update multiple report statuses endpoint. DONE!
* Bulk upload --> Publish
   * From Review page --> click Publish, what actually happens? Do all Reports get published? 
    * Will need /spreadsheets POST to return list of ALL report ids, both those that were created and those that were updated
    * Want to use update multiple report statuses endpoint
    * This flow does NOT need get reports by ID because /spreadsheets POST already returns relevant datapoints


Quick summary:
* To get Metrics for a Report, we first fetch all Datapoints for the Report, and then we massage/convert them into Metrics
* Redundant to send frontend BOTH metrics and datapoints -- never want to do that
* Should always choose between one or the other
* get reports by ID is being used to power Review page, so should just return datapoints

**Comment by mxosman** [comment]
I think it's safe to close this - please feel free to reopen if not!
