### ISSUE TITLE
Update logic of when "Add Data" step shows in Guidance

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#503]
@hobuobi and I noticed something today that we should update in the Guidance logic! Here's now to repro:

1) Create a new agency on staging (can do via admin panel)
2) Fill out all metric config
3) The "Add Data" step gets skipped and you go straight to "Publish Data"

I believe this is because, when new agencies are created via the admin panel, we automatically create a bunch of blank reports for them, and so the "Add Data" step thinks we already have data. However, all of the reports are in Not Started state.

Can we update the logic of that step so that only Draft reports count?

**Comment by mxosman** [comment]
Can do! Thank you for clarifying this step!
