### ISSUE TITLE
[Frontend] Implement new validation strategies for publishing

### ISSUE THREAD

**Issue by mxosman** [Recidiviz/justice-counts#515]
Discussion reference: https://www.notion.so/recidiviz/Re-Lili-Mahmoud-s-question-on-bulk-validation-7a48fd77e7d1464a9d463510c0304c6d?pvs=4

Goals:
- **Clear non-number inputs**
- **Handle missing top-level metric**

**Comment by lilidworkin** [comment]
Moving this to icebox

**Comment by mxosman** [comment]
OK to close this or should we keep it open for future reference?

**Comment by lilidworkin** [comment]
Ah yea don't see a reason to keep it open, closing!
