### ISSUE TITLE
[Bug] Jails > Use of Force Incidents: shows blank metric definitions w/ reset-to-default link when none are present

### ISSUE THREAD

**Issue by mxosman** [Recidiviz/justice-counts#524]
Screen Recording 2023-03-31 at 11.10.32 AM: In the Metric Configuration for the **Jails** system and the **Use of Force Incidents** metric, the list of definitions (includes/excludes) does not render for this metric -- even though the backend sends the correct JSON list to render. Oddly, the only thing that does render is the `Choose Justice Counts Default Definition` button. When you click on a different metric and go back to it, the metric definitions list renders fully.

**Steps to reproduce**:
1. Go to the Jails agency
2. Go to Settings -> Metric Configuration -> Click on the Use of Force Incidents -> Check the right side panel and you'll see the issue
3. Click on a metric like **Post-adjudication Releases** and then click back on **Use of Force Incidents** and the definitions reappear

https://images.zenhubusercontent.com/529290376/aa7410fa-e4ee-43bc-b727-07e9dcdac8ef/screen_recording_2023_03_31_at_11_10_32_am.mp4

**Comment by lilidworkin** [comment]
This could also be a BE / TIG thing if there are actually supposed to be includes/excludes for this? cc @morden35

**Comment by morden35** [comment]
This is strange. Looking into this now. Jails Use of Force Incidents should have includes/excludes.

**Comment by morden35** [comment]
strange behavior. When I initially click into 'Use of Force Indidents' I see the following (no includes/excludes)
<img width="1410" alt="Screenshot 2023-03-29 at 3 41 55 PM" src="https://user-images.githubusercontent.com/82831800/228662484-1f2c0b1d-3855-4795-92ad-cf8254c59d32.png">

Then when I click on another definition, for example 'Grievances Upheld', and then click back to 'Use of Force Incidents', the incl
<img width="1426" alt="Screenshot 2023-03-29 at 3 43 25 PM" src="https://user-images.githubusercontent.com/82831800/228662664-3789e326-6117-4598-b408-2a3bbc6d3262.png">
udes/excludes appear

**Comment by morden35** [comment]
I think this might be a FE bug because I do see a response with populated json from the GET request to /agencies/151/metrics.

**Comment by lilidworkin** [comment]
Cool, thanks for sanity checking that @morden35 ! Would you actually mind writing up a bug report ticket in the justice-counts repo for Ivan to look into this? @mxosman has his plate full at the moment and it might be a good candidate of something for Ivan to investigate!

**Comment by mxosman** [comment]
Just took a quick peek out of curiousity and +1 to @morden35's assessment - it looks like it is FE because the BE is sending all of the metric includes/excludes - there's just something weird with them not rendering initially. I wonder why it's just that metric, though.

I'm happy to flesh out this task if you haven't already filed a ticket @morden35!

**Comment by morden35** [comment]
> Just took a quick peek out of curiousity and +1 to @morden35's assessment - it looks like it is FE because the BE is sending all of the metric includes/excludes - there's just something weird with them not rendering initially. I wonder why it's just that metric, though.
> 
> I'm happy to flesh out this task if you haven't already filed a ticket @morden35!

I have not filed a ticket yet but happy to do so!

**Comment by mxosman** [comment]
Done and done! @ivan-kishko - let me know if you have any questions about this!
