### ISSUE TITLE
JC Admins should be able to see Records / Bulk Upload during Guidance

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#528]
@mxosman  is it possible to make a chance so that JC Admins can always see Records + Bulk Upload in the navigation, even when they are in the Guidance flow? Let us know if that's really tricky. Thank you!

**Comment by mxosman** [comment]
Yes - this is definitely possible! We just have to remember that we won't be able to test those menu items only popping up/activating within their respective guidance steps (as a user would experience them) with our JC admin accounts.

**Comment by lilidworkin** [comment]
Great call @mxosman -- I think that's fine but definitely something to keep in mind!
