### ISSUE TITLE
[Dashboards] Create table of contents for Agency Dashboards

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#597]
Right now, you have to know the agency ID in order to navigate to a particular agency's dashboard (e.g. https://justice-counts-agency-dashboard-web-qqec6jbn6a-uc.a.run.app/agency/147). This makes it really hard to test things out!

It'd be nice to have a "homepage" (fine if this is ugly, since it would be internal only) at https://justice-counts-agency-dashboard-web-qqec6jbn6a-uc.a.run.app that links out to all the different agencies, to make it easy to flip through them and test out how the dashboard looks on different kinds of data.

To do this, we'd need a new backend endpoint (without auth_decorator, since this is for the public dashboard) that returns a JSON structure sort of like this:

```
"agencies": [
   { "name": XXX, "id": XXX},
   { "name": XXX, "id": XXX},
]
```

We should be able to use the backend method `get_agencies_by_id` to accomplish this.

The frontend could then use this to render a list of URLs.

An extension of this task, to make this homepage even more useful potentially, would be to indicate next to each agency's name whether it has any published data, and if so, for how many metrics. To do this, we'd need to extend the backend endpoint to look more like this:

```
"agencies": [
   { "name": XXX, "id": XXX, "number_of_published_metrics": XXX},
]
```

To do this, we could re-use some of the logic from the `get_agency_published_data` endpoint. We won't need to re-use all of it, because we don't actually need to return all the published datapoints -- we just need to know whether any exist and if so how many.

**Comment by lilidworkin** [comment]
@mxosman filing this based on what we talked about earlier -- no urgency on this at all, fine if you don't even get around to it, but just wanted to jot it down before I forgot!

**Comment by mxosman** [comment]
Thank you so much for this detailed ticket! Everything makes sense and am looking forward to exploring this!
