### ISSUE TITLE
[Frontend] Refactor logic in `DefinitionModalForm`

### ISSUE THREAD

**Issue by mxosman** [Recidiviz/justice-counts#598]
The logic in `DefinitionModalForm.tsx`  is handling a lot of complexity and could use some refactoring & general clean up to make it easier to read, work within and more optimal.

How can we accomplish this? Always feel free to run with any ideas you have! Here are my thoughts/ideas below on areas I think could use some love:

1. We can better organize these variables - either by grouping related pieces together or even grouping booleans together, other vars separately.

<img width="725" alt="Screenshot 2023-06-01 at 10 54 57 AM" src="https://github.com/Recidiviz/justice-counts/assets/59492998/5278bf6c-f7d1-406c-8a4c-53a25aee9138">

---

2. Can we use a different data structure so we're not continuously traversing the nested object, remapping values, and generally avoid the nested reducers? Ideally, a flattened data structure if possible - happy to brainstorm together on a good solution.

<img width="678" alt="Screenshot 2023-06-01 at 11 11 21 AM" src="https://github.com/Recidiviz/justice-counts/assets/59492998/e2ebfd2b-1842-40a2-af50-62f13189edd2">

---

3. We can consolidate the logic here and just use conditionals for which object to do the `Object.entries` on and the `display_name` vs `label`

<img width="565" alt="Screenshot 2023-06-01 at 11 25 16 AM" src="https://github.com/Recidiviz/justice-counts/assets/59492998/378c352a-74bf-423c-b3d6-b4d7a147003d">

---

4. The components in the `hasNoSettingsAndNoContext` conditional are too similar to the ones in the render - I think we can consolidate this with the render and use conditionals there to render the `hasNoSettingsAndNoContext` copy.

<img width="581" alt="Screenshot 2023-06-01 at 11 04 27 AM" src="https://github.com/Recidiviz/justice-counts/assets/59492998/d484664e-5314-4f6b-b68e-dfa4cb55506c">

---

5. Nit: can we add just a couple comments in the render to help see the settings and context? 
(e.g. `{/* Includes/Excludes Settings */}` and `{/* Contexts */}`)

---

6. Anything else you feel will help make this file less confusing/easier for someone with little context to work within.

**Comment by ivan-kishko** [comment]
Hello @mxosman. About second point, what do you mean by using different data structure? Like make changes in store? or just refactor this function so there are no nested mappings? I mean the only reason it has nested reduce is because when we save settings we need this object to be like that (I mean object inside object) so we have all data for saveSettings function

**Comment by mxosman** [comment]
>or just refactor this function so there are no nested mappings? I mean the only reason it has nested reduce is because when we save settings we need this object to be like that (I mean object inside object) so we have all data for saveSettings function

Hey @ivan-kishko! I mostly meant this ☝️ if and wherever possible. I'm just wondering if there's a better way to express/structure this - maybe there isn't!
