### ISSUE TITLE
[Superagencies] Superagencies should not be able to create reports or enter data

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#607]
We need to change the following pages in the app to improve the experience for superagencies. (Note -- the FE should be able to determine whether the current agency is a superagency, and if so the names of its child agencies, based on the backend PR [here](https://github.com/Recidiviz/recidiviz-data/pull/21087/files)).

## Home Page
* Should contain a single data card directing the user to bulk upload. ([Figma](https://www.figma.com/file/0UZOuDCrwGqWLKOhAyvGbc/Forrest's-First-Figma-File-(FFFF)?type=design&node-id=1122-41965&t=JO7REvvtbndnliu4-0))

## Data Entry Tab in Nav Bar
* Rename to Data Upload
* Goes straight to bulk upload

## Data Page
* Link out to child agencies ([Figma](https://www.figma.com/file/0UZOuDCrwGqWLKOhAyvGbc/Forrest's-First-Figma-File-(FFFF)?type=design&node-id=1122-41965&t=JO7REvvtbndnliu4-0))
* We will likely need to adjust the backend response to send the child agency IDs instead of the child agency names -- that was an oversight on my part but should be an easy fix :)

**Comment by lilidworkin** [comment]
@mxosman this is for AFTER the home page and nav is all done. No rush!! Just getting it off of my plate :)

**Comment by mxosman** [comment]
Sounds great - thank you, Lili!

**Comment by lilidworkin** [comment]
Closing this -- we need to revisit product/design in light of https://app.zenhub.com/workspaces/justice-counts--622109ea3bb6e0001d2d06ad/issues/gh/recidiviz/recidiviz-data/22129
