### ISSUE TITLE
[Internship] [Superagencies] Superagency Bulk Upload templates

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#617]
If you’re are a superagency, the bulk upload template you see/download should have an agency column, and the instructions for bulk upload should be updated accordingly.

**Comment by lilidworkin** [comment]
Will be part of intern project

**Comment by lilidworkin** [comment]
@nichelle-hall you're working on this right?

**Comment by nichelle-hall** [comment]
Yep! I have one more open PR.

**Comment by nichelle-hall** [comment]
Or actually, this part of the task is done. The last PR is for generating single-page templates. I'll close this ticket.
