### ISSUE TITLE
Conduct an audit of permissions to find and gate ungated UI components

### ISSUE THREAD

**Issue by mxosman** [Recidiviz/justice-counts#628]
We have some UI components that raise permissions errors in the backend that are not properly gated in the FE. The goal here is to do an audit of the set of permissions we have and map them to what components should be rendered/gated so we can identify and resolve any discrepancies we currently have and ensure users without permissions to update something in the FE don't see the UI component rendered at all.

Discrepancies identified:  
* [Resolved in [#629](https://github.com/Recidiviz/justice-counts/pull/629)] Need to gate "Edit populations ->" in Agency Settings for users who are not JC Admins

**Comment by mxosman** [comment]
I'm debating closing this - @lilidworkin - do you think this is still worth pursuing? I feel like we're OK for now - there hasn't been anything surfaced since this (maybe updating the Delete records permissions?) (and, totally recognizing this doesn't necessarily mean we got everything covered - but I can't think of anything else off permissions wise with our components). Happy to keep it open if you think it'll still be good to do at some point!

**Comment by lilidworkin** [comment]
I'm good closing this! I totally agree that we can reprioritize if it comes up again!
