### ISSUE TITLE
Bulk Upload review page Adjustment

### ISSUE THREAD

**Issue by jwhrec** [Recidiviz/justice-counts#657]
Current design [here](![Screenshot 2023-05-24 at 11.57.16 AM.png]

(https://images.zenhubusercontent.com/6425f94625a44e8ff4f2b570/c1e9df0b-c227-4bbe-a3b8-755f49aefea2)https://www.figma.com/file/brkAAatBCcvSnLJOIxZJIM/recidiviz-x-allison?type=design&node-id=883-5720&t=5dqBGvIV7FrYQpMh-0)

Currently, this page only shows data for a single agency. However, we have recently made it possible to bulk upload data for multiple agencies at the same time. I’m wondering if there’s a super super simple, lightweight adjustment we can make to this page to basically repeat the chart on the right side multiple times, once for each agency.

Like
Agency Name 1
Releases
Admissions
Expenses
…
Agency Name 2
Releases
Admissions
Expenses
…

Or, alternatively:
Releases
Agency Name 1
<chart>
Agency Name 2
<chart>
…
Admissions
Agency Name 1
<chart>
Agency Name 2
<chart>
…

**Comment by lilidworkin** [comment]
Done
