### ISSUE TITLE
[Bug][Frontend] Sometimes when you click on the Data Viz page and click on another link, it briefly takes you to your destination and suddenly snaps you back to you back to the Data Viz page

### ISSUE THREAD

**Issue by mxosman** [Recidiviz/justice-counts#677]
There is a strange intermittent bug when you click to go to the Data (visualization) page and go to another page - there are moments when you get redirected back to the Data page. It doesn't happen all the time and there's no clear way to trigger this. Some times it takes a few seconds before you get snapped back, sometimes it happens immediately, sometimes not at all. It feels like there's something funny going on with either the routing or some state that the Data page updating after you leave that page. I was able to capture a video of this behavior happening a couple of times:

https://github.com/Recidiviz/justice-counts/assets/59492998/e3f46adf-2536-4182-b7c4-3ff8e849012e

**Comment by ivan-kishko** [comment]
I Identified the problem, but looks like solution will not be an easy ride

**Comment by mxosman** [comment]
Ah - thanks for investigating and for the explanation. Dang - was hoping it would be a simple adjustment! Please feel free to deprioritize this in favor of the Agency Dashboard work. Will also assign myself to look into later.

**Comment by ivan-kishko** [comment]
Configuration page fixed, Data page is not yet
