### ISSUE TITLE
Nit #10: Change heading on Data Entry page

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#699]
Item 10 in this [Figma file](https://www.figma.com/file/0UZOuDCrwGqWLKOhAyvGbc/Forrest's-First-Figma-File-(FFFF)?type=design&node-id=1173%3A45776&t=vmxUwNJ53SY7d0fk-1)

**Comment by ivan-kishko** [comment]
@lilidworkin Hello. Can someone ask @forrestkim00, maybe you, should "Enter data" stay visible as well, cause description says that date should not shrink but on a screenshot "Enter data" is also visible so I am not sure how to make it exactly right

**Comment by ivan-kishko** [comment]
@lilidworkin Hello. Can someone ask @forrestkim00, maybe you, should "Enter data" stay visible as well, cause description says that date should not shrink but on a screenshot "Enter data" is also visible so I am not sure how to make it exactly right

**Comment by lilidworkin** [comment]
Good question -- I think Enter Data should stay visible, along with the date, but @forrestkim00 can confirm!
