### ISSUE TITLE
Flesh out part 1.4 of Claire's project

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#709]
@mxosman can I trouble you to flesh out a small part of Claire's intern project? It's the part [here](https://docs.google.com/document/d/15VdzSbKCOwJLAJu8OxuL4Aq0ezykOz7XBq-ZHuF9VE8/edit?disco=AAAAyqJmu38). The level of detail should be similar to what Nichelle wrote out above for the other parts -- somewhat detailed / hand-holdy, but you can definitely leave some gaps. 

The idea is we're going to build a backend endpoint to serve the bulk upload template files. So when you click the "Jails: Download" button on the instructions page, instead of downloading a static file, it should call the backend endpoint and download the file it receives from that. We do something similar for downloading files on the Uploaded Files page I think? So we can likely just copy whatever pattern we use there. (Feel free to say that and link to that!) 

It's a pretty simple task, but not trivial -- we'll have to figure out which store to put the call to the new backend endpoint, etc, and then replace the simple HTML link that we have now with a call to this endpoint. Feel free to make whatever design decisions you think are best! Let me know if you have any questions.

**Comment by mxosman** [comment]
Absolutely!
