### ISSUE TITLE
Add "Read Only" label to Team Management page

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#712]
Currently, on the Team Management page, we have little labels that say "Invited", "Admin", or "JC Admin":

![Screenshot 2023-06-15 at 1.05.13 PM.png](https://images.zenhubusercontent.com/620e7d8c0c5fad82d897844d/c0099dbd-6520-4cf1-beb2-bcde17f54d02)

Let's add one for the new "Read Only" role. If a user has the Read Only role, it should say "Read Only" in grey text next to their name. You can pick a shade of grey that looks good to you -- something not too light and not too dark :D

To test it out, you can use Clackamas County Jail -- Lili has Read Only status there!

**Comment by morden35** [comment]
> @morden35 what do you think of this? I realized it might get tough to debug things if we start hiding people from this list depending on role combinations, but at least this way we're being transparent and it will distinguish the CSG folks from the agency folks.

Yeah that sounds good to me! I like the idea of transparency

**Comment by morden35** [comment]
Maybe we can also add a tool tip that explains what 'Read Only' (and the other roles) implies
