### ISSUE TITLE
New landing page for users with multiple agencies

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#748]
If a user belongs to multiple agencies, then when they load the app, instead of just showing the first agency in the list like we [currently do](https://github.com/Recidiviz/justice-counts/blob/9353187d06070d4fb8bf5cd1bfa8db9510558224/publisher/src/stores/UserStore.ts#L130), we'd like to show this new landing page: [Figma](https://www.figma.com/file/0UZOuDCrwGqWLKOhAyvGbc/Forrest's-First-Figma-File-(FFFF)?type=design&node-id=1591-45146&mode=design&t=Hf0kOGUxqtJPDHml-0) (If a user only belongs to one agency, don't show this landing page.)

General idea:
* We should group the agencies that the user belongs to by state
* Each agency gets its own "box". When you click the box, we should navigate to the Records page of that agency.
* There are two dropdowns that let you filter by State and by Sector. They should be multi-select. The page should update to only show agencies that belong to the selected states/sectors.

A few adjustments to the mocks:
* The title should say "Welcome to Publisher", not "Welcome to Agency Dashboards"
* Ignore the blue text under the agency name that says "1 Published Metric". The box should just contain the agency name. 
* Ignore the [Entry Point mock](https://www.figma.com/file/0UZOuDCrwGqWLKOhAyvGbc/Forrest's-First-Figma-File-(FFFF)?type=design&node-id=1613-43924&mode=design&t=VZ6yANff2F8m2Vgj-0) for now -- that depends on a header redesign that Mahmoud is working on.

There are likely some parts of this task that need to be fleshed out further, so if you run into any obstacles, just ask!

**Comment by morden35** [comment]
@lilidworkin is it safe to close this ticket?

**Comment by lilidworkin** [comment]
Haha yes, thanks @morden35 !! Will close
