### ISSUE TITLE
[Backend] Create API to fetch datapoints for agency dashboard

### ISSUE THREAD

**Issue by terryttsai** [Recidiviz/justice-counts#77]
The Agency Dashboard is a Justice Counts frontend app that fetches and displays Justice Counts data published by Justice Counts Agencies. 

The app will be deployed on Justice Counts Agency websites (like Spotlight). I think it can also possibly be hosted by CSG and fetch from different agencies?

So we need an endpoint for the app to access to fetch published JC data. We currently have the `justice-counts` backend app in `recidiviz-data` that requires Auth0 auth from either a Recidiviz member or a registered JC member of the agency to fetch agency data. 

Should we open up a public endpoint in `recidiviz-data` to fetch published data without requiring Auth0? Or is that too big of a security issue? Should we research using [machine-based auth](https://auth0.com/docs/get-started/authentication-and-authorization-flow/client-credentials-flow), as per Lili's suggestion, to authorize the app without requiring user sign-in? 

Should we create a new backend service that only contains published data? (Something we might build in the future for the JC Aggregator Service)

**Comment by terryttsai** [comment]
Estimate of 2-3 as in probably will take a work day to build

**Comment by terryttsai** [comment]
@hobuobi should we make sure only published datapoints are in agency dashboard? No drafts?

**Comment by hobuobi** [comment]
Short answer: yes! 
The flip side of this is that we should probably 1) distinguish between draft and published datapoints in Publisher, and 2) prompt users to publish data sooner rather than later. But we can deal with these separately.

**Comment by terryttsai** [comment]
This is closed by https://github.com/Recidiviz/recidiviz-data/pull/16088
