### ISSUE TITLE
[Agency Dashboard] Only allowlisted agencies should have a dashboard (all others 404)

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#771]
Allowlist is here: https://docs.google.com/document/d/1ga2GWL8MnEJLkzzjt5DlBJdJSyKf_-fgVzXn2-IBPCw/edit

This sort of blocks on https://app.zenhub.com/workspaces/justice-counts--622109ea3bb6e0001d2d06ad/issues/gh/recidiviz/recidiviz-data/22171, but we can still get started on this by creating a dummy allowlist.

**Comment by alfonsogoberjr** [comment]
Hey @lilidworkin I still need access to the doc at https://docs.google.com/document/d/1ga2GWL8MnEJLkzzjt5DlBJdJSyKf_-fgVzXn2-IBPCw/edit

**Comment by mxosman** [comment]
Hey @alfonsogoberjr - just shared the doc with you - lmk if you still can't access it!
