### ISSUE TITLE
[Agency Dashboard] Figure out what to do with landing page

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#772]
i.e. the / route, where we currently have the nice landing page that Mahmoud designed. This is what people will see when they just go do dashboard.justice-counts.org. We're waiting on Katie to tell us what this should be.

Maybe keep the landing page on Staging only?
Eventually have an Auth-only landing page?

**Comment by lilidworkin** [comment]
@mxosman is it easy to just hide this page on production for now (but keep it on staging) -- i.e. if you go to the home route ("/") it just shows a blank page or a 404? Ideally it would also avoid making the query to the backend API in that case too.

If that's not hard, would be great if you could go ahead on it sometime this week! I don't think we're going to be getting any other guidance from Katie any time soon haha.

**Comment by mxosman** [comment]
Hi Lili! I think so - I'll give it a shot! Sounds great!

**Comment by mxosman** [comment]
Wasn't too bad at all!
