### ISSUE TITLE
[Frontend][Edge case] Revisit homepage all-tasks-completed copy when user marks all metrics as 'Unavailable'

### ISSUE THREAD

**Issue by mxosman** [Recidiviz/justice-counts#775]
In the home page, when a user marks all metrics as 'Unavailable', no metric cards are generated and thus the user ends up in an "All tasks completed" state. In these states, the copy currently reads "Dashboards are updated with the latest published records" - which works when records are published. But, when you've simple disabled all metrics and/or have no published records, it doesn't read true.

There are a couple of solutions to this I can think of:
1. Update the "Dashboards are updated with the latest published records" copy to satisfy all cases
2. Add different copy for the cases where all metrics are disabled and update the subtitle based on these different states

**Comment by lilidworkin** [comment]
Just going through and making sure all tasks have owners

**Comment by lilidworkin** [comment]
De-pri
