### ISSUE TITLE
Right align metric numbers in Review Page

### ISSUE THREAD

**Issue by jwhrec** [Recidiviz/justice-counts#794]
Currently the metric numbers are center aligned in the review page. They should be right aligned for easier comparison and readability 

![Screenshot 2023-07-27 at 5.06.39 PM.png](https://images.zenhubusercontent.com/6425f94625a44e8ff4f2b570/f979341f-0d9b-44fc-a4a1-985cde289a53)

**Comment by lilidworkin** [comment]
Another small task!
