### ISSUE TITLE
[Agency Dashboard] Look into new issue where 404s pages aren't being shown

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#812]
Might have to do with @alfonsogoberjr 's changes?

**Comment by alfonsogoberjr** [comment]
Do we know which agencies are 404ing?

**Comment by alfonsogoberjr** [comment]
This is addressed by https://github.com/Recidiviz/justice-counts/pull/821 which is still waiting for #819 (and an approval) per Slack
