### ISSUE TITLE
[Publisher] Design Nit: Changing PNG Download

### ISSUE THREAD

**Issue by mxosman** [Recidiviz/justice-counts#872]
Adjust the PNG download of Data Viz chart to include metric name and breakdown legend. Note: we might have to use another library for this (see exploration below).

Figma: https://www.figma.com/file/UQkS5kLvJZMHRuDp8h7kiD/Nits-to-Cleanup?type=design&node-id=27%3A47&mode=design&t=bD0W3U2B1cve5l6i-1

Ivan's exploration feedback:
>Nit #1 So about this. With recharts-to-png you cannot have legend metric name and padding inside image. Why? Because recharts-to-png converts only svg element to png. It does not care about containers, legends etc. So the solution might be to use html2canvas library (recharts-to-png is built on top of it). As far as I understood it takes element by id from page and converts it to png. So you can wrap inside data page metric name chart and legend and use this container to make png, BUT between metric name and chart there are filters. And since html2canvas takes all inside container they will be on a png. Maybe you can apply styles on download event click and then switch styles back, I read something about it but not sure for now is it possible and how it will affect UI, like you might see those changed styles for a split second or smth like that. All other nits are done.

**Comment by lilidworkin** [comment]
De-pri
