### ISSUE TITLE
Prosecution and Prosecution [DEMO] dashboards are erroring in staging

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#887]
Go to either of these agencies and then click "Understand the Finances":

https://dashboard-staging.justice-counts.org/agency/prosecution-%5Bdemo%5D
https://dashboard-staging.justice-counts.org/agency/prosecution

It's quite possible that the underlying cause comes from the backend, so feel free to rope in Michelle or Lili once we have a diagnosis.

Might be the same error as https://app.zenhub.com/workspaces/justice-counts--622109ea3bb6e0001d2d06ad/issues/gh/recidiviz/recidiviz-data/22940, or might be different? If it looks like the same one, then @alfonsogoberjr feel free to catch @mxosman up on any debugging you've already done so we don't duplicate efforts!

**Comment by mxosman** [comment]
Closed by #885 and #891
