### ISSUE TITLE
Create demo-able dashboards for all sectors

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#889]
As show in the tracker [here](https://docs.google.com/document/d/1AMq36vUvUIj_yEjNtjLbGFXjU8ttNk8u3MSqLRnHPoE/edit#heading=h.lg3s48ernkp8), we currently have demo-able dashboards for Prisons (Department of Corrections) and Law Enforcement (Law Enforcement [DEMO]). We want to have demo-able dashboards for all sectors (in Staging). We can just use the [DEMO] agencies that already exist. So the only thing we need to do is add fake data for the Capacity and Costs metrics for the past few years. We can use the same numbers we've used for Department of Corrections.

**Comment by mxosman** [comment]
Sounds great, Lili!

**Comment by mxosman** [comment]
All sectors now have demo-able dashboards and tracker has been updated!
