### ISSUE TITLE
Require all PRs to have labels like we do in `recidiviz-data` (e.g. Type: Bug, Type: Feature, etc)

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#9]
Just add this workflow: https://github.com/Recidiviz/recidiviz-data/blob/main/.github/workflows/require_labels.yml

**Comment by lilidworkin** [comment]
@mxosman would you mind knocking this out? I think it should be deadsimple, just a matter of copying/pasting the workflow linked in the description. Thanks!

**Comment by mxosman** [comment]
Absolutely! Thank you for the example!
