### ISSUE TITLE
4.1.4.1 Long Session Timeout

### ISSUE THREAD

**Issue by phenggeler** [Recidiviz/justice-counts#915]
#### CVSS Score: 3.9
OWASP Top 10 Reference: A7:2021 - Identification and Authentication Failures
URL: https://publisher-staging.justice-counts.org

> Description: User sessions extend beyond the recommended 60-minute interval. After logging in
> as a user and performing no actions for over 90 minutes, I observed that resuming operations
> after this time did not cause the system to log out the user and send them back to the login page.
> Waiting longer does eventually trigger a session timeout, but it was observed that the user simply
> has the JWT token refresh without having to re-enter their password, which goes against best
> practices for session timeouts.

References:
● https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#idle-timeout

Remediation: Set the session timeout to a maximum of 60 minutes of inactivity.

Supporting Evidence:
Log in to the Justice Counts application and wait 90 minutes before trying to access another
page. There will be no requirement to log in as the session does not expire due to inactivity.

**Comment by mxosman** [comment]
<img width="977" alt="Screenshot 2023-09-06 at 12 01 12 PM" src="https://github.com/Recidiviz/justice-counts/assets/59492998/1f55efd5-c590-47b2-9b6b-12161fe4223c">

So, I just set the **Inactivity timeout** and **Require log in after** to 60 minutes and am testing now. I'm hoping - especially after setting the **Require log in after** - that if a user has the DE page open and is inactive for 60 minutes, they're automatically redirected to the login screen.

**Comment by mxosman** [comment]
Interesting - so I was able to continue typing in values and it saved, but I foolishly refreshed for some reason and I was redirected to the login screen. I'm assuming navigating away would've triggered the redirect as well. Testing this again, and will try to screen record this time and see about the the navigating away & why edits are still saving.

**Comment by lilidworkin** [comment]
@mxosman if the changes actually successfully saved, I think it's fine actually?! I was just worried they wouldn't save and the user would lose data

**Comment by mxosman** [comment]
OK! We're cooking now! I tested again and updated the `Token Expiration` for #916 to be 15 min. Here's what happens after an hour of idle:

https://github.com/Recidiviz/justice-counts/assets/59492998/99cd516e-5816-4de9-8507-d72f3bb690bd

Worth noting that it still saved the change before erroring and redirecting.

I'm going to test again for just 15 min just to make sure the token expiration doesn't cause any weirdness.

**Comment by mxosman** [comment]
> @mxosman okay awesome! So just to confirm and make sure I'm following:
> 
> * You updated both the inactivity timeout (to 60 mins) and the JWT token expiration (to 15 minutes) and tested and everything seems fine.

Confirmed! The session times out after 60 minutes and any action the user takes redirects them to the login screen.

> * The behavior after 60 minutes of idle is that if the user tries to make a change, we error and redirect them to the login page. We don't think the change will save in this case (but whether it does or doesn't, it doesn't matter too much in my mind).

Confirmed! I can also confirm both times no PATCH request was sent to make the update and save (I must've not have been fully paying attention when I assumed that it did save the value). 

> If this is all true, then I think we can go ahead and make the corresponding changes to the prod tenant, close out the tasks, and let Peter know the pen testers can try again!

Sounds great - will do! I'll follow up and close both issues once prod has been updated.

**Comment by mxosman** [comment]
"Inactivity timeout" and "Require login after" have been set to 60 minutes in both staging and prod via Auth0.

**Comment by lilidworkin** [comment]
@mxosman  Going to change "Require login after" to be greater than 60 minutes as per Stephanie's comment [here](https://recidiviz.slack.com/archives/C04JL8A2ADB/p1696529807482389). I think the goal of this task was just to set the inactivity timeout to 60 minutes -- we can use a longer timeout if the user is active!

**Comment by lilidworkin** [comment]
As per https://recidiviz.slack.com/archives/C04JL8A2ADB/p1697122803462659?thread_ts=1696529807.482389&cid=C04JL8A2ADB, we actually don't want to log out people who are still active after 60 minutes, so we want to set "Require login after" back to whatever it was before or whatever the default is. @morden35 would you mind looking into this?

**Comment by morden35** [comment]
In Settings > Advanced > Login Session Management > Require log in after (Regardless of activity, users will be forced to log in after the period (max. 365 days)), I adjusted this value from 60 minutes to 1440 minutes (24 hours) in both Staging and Production

<img width="1012" alt="Screenshot 2023-10-12 at 1 30 30 PM" src="https://github.com/Recidiviz/justice-counts/assets/82831800/24c73785-be9a-4ae1-9df2-cf9ddf639a3b">

**Comment by morden35** [comment]
> > In Settings > Advanced > Login Session Management > Require log in after (Regardless of activity, users will be forced to log in after the period (max. 365 days)), I adjusted this value from 60 minutes to 1440 minutes (24 hours) in both Staging and Production
> 
> Oh goodness - great catch! I have a feeling it was defaulted to 1440 until I changed it to 60 min. My bad - thank you for the fix and the documentation of the adjustment!

all good! this is definitely a trial and error kind of thing
