### ISSUE TITLE
4.1.4.2 Long JWT Token Expiry

### ISSUE THREAD

**Issue by phenggeler** [Recidiviz/justice-counts#916]
#### CVSS Score: 3.1

OWASP Top 10 Reference: A5:2021 - Security Misconfiguration
URL: https://publisher-staging.justice-counts.org

> Description: After logging out of the application, the JWT bearer token is still valid, thus allowing
> API calls to be made. Since the JWT expiry is greater than the recommended 15 minutes, there is
> an element of risk associated with someone being able to use this same token even after the user
> has logged out of the system.
> 

References:
● https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.ht
ml#manual-session-expiration
Remediation: Consider monitoring the state of valid tokens on the server side, and invalidating
tokens when the user logs out from the application to prevent this type of abuse. Another
remediation approach would be to limit JWTs to be valid for 15 minutes at most.
Supporting Evidence:
Using the JWT extension for Burp Suite, the expiry date for the JWT token can be seen below:
<img width="676" alt="image" src="https://github.com/Recidiviz/justice-counts/assets/10621768/9f9d6872-fb4b-45a3-aaeb-d56d42d15047">

<img width="717" alt="image" src="https://github.com/Recidiviz/justice-counts/assets/10621768/e8a8dec3-e02d-4d2e-becb-00259eadf0ec">

**Comment by phenggeler** [comment]
One thing to note - the Polaris team had a very similar [finding](https://github.com/Recidiviz/zenhub-tasks/issues/927) last year. I believe that we ultimately were able to address this by simply modifying the token expiration to be 15 minutes - this might be an Auth0 setting, but I can't recall offhand. Anyway, I wanted to link to that finding since it might help work on this one.

**Comment by phenggeler** [comment]
> @phenggeler could we also just ensure that we invalidate the token after logout, as per instructions here?

Yes, that would absolutely work @lilidworkin!

**Comment by mxosman** [comment]
Token expiration has now been set to 900s (15 minutes) in staging and prod via Auth0.

**Comment by lilidworkin** [comment]
@mxosman , @phenggeler It seems like maybe this is making it so that we log out users after 15 minutes, even if they are active (as per comment [here](https://recidiviz.slack.com/archives/C04JL8A2ADB/p1696529807482389). I don't think that's expected, is it?

**Comment by phenggeler** [comment]
> @mxosman , @phenggeler It seems like maybe this is making it so that we log out users after 15 minutes, even if they are active (as per comment [here](https://recidiviz.slack.com/archives/C04JL8A2ADB/p1696529807482389). I don't think that's expected, is it?

@lilidworkin - Oh, interesting. I wouldn't expect that we would log any active users out - only those users that have been inactive for 15 minutes.

**Comment by lilidworkin** [comment]
Actually yea, it's just inactive users. But still was that the intention? For inactive users to be logged out after 15 minutes? I thought the intended outcome was that we'd make another call to Auth0 to get a new token after 15 minutes. cc @danawillow -- wondering if you can help confirm this, since you did the [same thing](https://github.com/Recidiviz/zenhub-tasks/issues/927) for Polaris? Thank you so much!

**Comment by danawillow** [comment]
According to https://github.com/Recidiviz/recidiviz-dashboards/issues/3403#issuecomment-1569096723 we specifically need a 15 minute logout based on state-specific requirements. If you don't have anything like that you probably could refresh the token instead of logging them out?

**Comment by phenggeler** [comment]
@lilidworkin - good question. This finding was not about session expiration for inactive users - sorry for not being clear about that. The original point of this finding was that if somebody logged out, the JWT token would either immediately be killed or would expire within 15 minutes. 

A related but different finding we have seen on our pentests in the past is that a user could leave a website up in their browser for several hours without the session expiring. Polaris has specific requirements to enforce a 15-minute timeout, but that doesn't apply to Justice Counts. I'd suggest some sort of session expiration, but it could be greater than 15 minutes.

Polaris had to handle both of the above requirements, while only the first one applies to JC. @danawillow - did the "Are you still using this app?" feature [here](https://github.com/Recidiviz/recidiviz-dashboards/issues/3403#issuecomment-1569288380) work? I wonder if that might be a solution here.

**Comment by danawillow** [comment]
> did the "Are you still using this app?" feature https://github.com/Recidiviz/recidiviz-dashboards/issues/3403#issuecomment-1569288380 work?

I didn't end up actually using that feature! I just did the base idle timer with a 15m logout, mainly because it was easier (we would have had to run the prompt by design and write css and stuff, which didn't seem worth it to me).

I think _before_ this we did set the JWT expiration in auth0 to be something short like 15 minutes- the issue was that we didn't build in auto-refreshing so if a user was active in our app (but not doing anything requiring an auth0 token) for 15 minutes then tried to make a call to the backend, it would fail because the token had expired. Just logging them out ended up being a more elegant solution (and also it turned out we had a requirement for it)

**Comment by mxosman** [comment]
Hi all! Thank you for the discussion and super helpful context. I was playing around with this and recently learned that the Auth0 `getTokenSilently` requires setting cookies as part of its authentication. With our settings (expiration set to 15 minutes), in a normal browser environment that allows third-party cookies, `getTokenSilently` goes through its flow and gets a new token and doesn't log out or interrupt the actions the user is taking. But, I tried staying idle for 15 minutes before taking an action in Incognito mode and Safari (whose upgrade privacy features by default block third-party cookies, I believe) - and it logged me out and back in to the same page (no actions I took were saved). The error was an Auth0 "Login required" error, which I learned comes from `getTokenSilently` failing to set a cookie. I tried to repro in my current Chrome browser that allows third-party cookies and it did not log me out - no hiccups in being able to take an action and that action saving.

I'll look back at our configuration just to triple check everything is set up properly - if so, I believe there are a few things we could try to accommodate those environments (using a different strategy than `getTokenSilently` - like rotating refresh tokens - will need to read more about this to get a better understanding of our options) - but, I'm wondering @phenggeler if you see any potential issues with us extending the JWT expiration beyond the 15 minutes to 60 minutes? It feels like it would be a much lower-lift if it feels secure enough to do vs. potentially refactoring our refresh token logic. Would love to hear your thoughts whenever you have time and energy!

**Comment by phenggeler** [comment]
@mxosman - 60 minutes sounds acceptable since Justice Counts does not technically fall under our existing customer or CJIS requirements. Session timeouts tend to come up on pentests, so we might hear about it in the future. Is there a place where you could add a comment inline that justifies the 60 minute timeout and points to this ticket? Or, does this all live in Auth0 configuration?

If the latter, that is fine. We will just need to remember it in the future.

**Comment by mxosman** [comment]
Thank you so much, @phenggeler! I'll keep digging into other options since this increase in time is not ideal - but good to know that it's acceptable. There isn't a place I have in mind to note this in the codebase - this would all be done in Auth0 - I could place it in one of our Auth files, but at the same time feel like I want to avoid advertising our JWT timeout in the codebase. I'll think of a good place to include this info so we don't forget before doing any adjustment to the time. Thanks again, Peter!

**Comment by phenggeler** [comment]
Thanks @mxosman - I don't know that you need to dig much further. I'm fine with a one-hour timeout if you all are, given that JC is largely dealing with public data.

**Comment by mxosman** [comment]
Thank you @phenggeler! Will find a good place to document before adjusting - I truly appreciate your help!
