### ISSUE TITLE
[Frontend][Agency Dashboard] Agency landing page and about page

### ISSUE THREAD

**Issue by terryttsai** [Recidiviz/justice-counts#94]
![Screen Shot 2022-10-18 at 3.51.00 PM.png](https://images.zenhubusercontent.com/623bb0d443429e7fa7d03621/d357df46-9c9c-400f-8672-0cc59cf1d43c)

**Comment by terryttsai** [comment]
Is this screen still relevant?

**Comment by lilidworkin** [comment]
@terryttsai  I don't think so -- we can close this task
